### ISSUE TITLE
Rexray won't start on Ubuntu Xenial

### ISSUE THREAD

**Issue by Farfaday** [codedellemc/rexray#1019]
# Summary
Cannot start rexray on Ubuntu Xenial :
```shell
$ curl -sSL https://dl.bintray.com/emccode/rexray/install | sh
Selecting previously unselected package rexray.
(Reading database ... 75619 files and directories currently installed.)
Preparing to unpack rexray_0.10.0-1_amd64.deb ... 
Unpacking rexray (0.10.0-1) ... 
Setting up rexray (0.10.0-1) ... 

rexray has been installed to /usr/bin/rexray

REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.0
OsArch: Linux-x86_64
Commit: c23d059e0a3e1dd43a517d5bf7d6f5032b13ded5
Formed: Mon, 11 Sep 2017 02:16:48 CEST

$ rexray volume ls -l
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/codedellemc/rexray/util.FindFlagVal(0x25e0aed, 0x2, 0xc420010180, 0x4, 0x4, 0x0, 0x24939a0, 0x1, 0x2, 0x90)
        /go/src/github.com/codedellemc/rexray/util/util.go:573 +0x23d
main.main()
        /go/src/github.com/codedellemc/rexray/rexray.go:64 +0x186
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```

## Version
Please paste the output of `rexray version`. For example:

```shell
# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.0
OsArch: Linux-x86_64
Commit: c23d059e0a3e1dd43a517d5bf7d6f5032b13ded5
Formed: Mon, 11 Sep 2017 02:16:48 CEST

```

### Service Log
empty (just the logo)

**Comment by akutz** [comment]
It's bad error handling, but it's because you're passing in the log level flag with no log level. I swore I checked for that index range possibility, but clearly I did not.

**Comment by akutz** [comment]
Hi @Farfaday,

Just out of curiosity, is there some documentation that you were using that showed the use of the `-l` flag sans an argument? I'm hoping it's just a typo and there isn't some documentation in error out there, but in case there is, I'd like to know what and where it is so I can fix it or reach out to the one who wrote it and have them fix it.

Thank you!

**Comment by Farfaday** [comment]
Hi,
having an empty config file (/etc/rexray/config.yml)

```
# rexray volume
Oops, an error occured!

  client must specify service

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/codedellemc/rexray
  - The on↓ine he↓p be↓ow
```

English is not my mother language, I misunderstood that documentation and thought the **-l** was only activating some debug feature (boolean). My bad.
Maybe listing the available debug levels would help people like me :D

Thank you for your work !

**Comment by akutz** [comment]
Hi @Farfaday,

Thank you for such a fast response! I think in a future update we can change the above text to:

```
- Debug output by using the flag "-l <log-level>", ex. "-l debug"
```

Does the above change make things more clear?

**Comment by Farfaday** [comment]
That sounds perfect! Many thanks!
