### ISSUE TITLE
docker: Enhance managed plug-in configuration options

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/rexray#1043]
The `config.json` file for each docker managed plugin lists all the allowed env vars for a plugin. Right now this list is restrictive, and is missing a lot of useful REX-Ray options, such as those for Linux file mode, options for data directory, etc.

We can either add more options to all plugins, but we can also explore auto-populating the vars from the output of `rexray env | grep <DRIVER>_`, plus some other standard ones.

- [ ] `HTTP_PROXY`

**Comment by akutz** [comment]
Related to #933.
