### ISSUE TITLE
"volume name must be unique" error when trying to run an EFS backed container

### ISSUE THREAD

**Issue by jicowan** [codedellemc/rexray#1046]
# Summary
I created a NFS volume, efsvol, using RexRay, e.g. `rexray volume create efsvol`.  I can mount the volume on the an EC2 instance, `rexray volume mount efsvol`.  The volume appears in the list when I enter `docker volume ls`.  However, when I try to run a container that uses that volume I get the following error: 
```
docker: Error response from daemon: create efsvol: found reference to volume 'efsvol' in driver 'rexray', but got an error while checking the driver: error while checking if volume "efsvol" exists in driver "rexray": Post http://%2Frun%2Fdocker%2Fplugins%2Frexray.sock/VolumeDriver.Get: dial unix /run/docker/plugins/rexray.sock: connect: connection refused: volume name must be unique.  
```
I ran the container using like this: 
`docker run -it -v efsvol:/data --volume-driver=rexray busybox sh`

I can mount the volume RexRay created using the `mount` command on each host so I know I'm able to connect to the volume. 
 
# Bug Reports
This section is for issues that relate to discovered problems or bugs.

## Version
Please paste the output of `rexray version`. For example:

```
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.2
OsArch: Linux-x86_64
Commit: 4c451f856336c83680cc250ff62998bc70876c40
Formed: Tue, 12 Sep 2017 21:18:02 UTC
```

## Expected Behavior
I would expect to be able to reference the volume by the name I gave it when I created it, i.e. *efsvol*

## Actual Behavior
I got an error saying `volume name must be unique`
If I reference the mount point on the docker host, the container runs without issue, e.g.
`docker run -it -v /var/lib/rexray/volumes/efsvol:/data busybox sh`

## Steps To Reproduce
Please list the steps to reproduce the issue in this section.

1. The first step should always be enabling `debug` logging.
  * Open the file `/etc/rexray/config.yml`
  * Set the log level for both REX-Ray and libStorage to `debug` and enable
HTTP request and response tracing for libStorage:
```yaml
rexray:
  logLevel:        debug
libstorage:
  logging:
    level:         debug
    httpRequests:  true
    httpResponses: true
```
* Please list each step with as much detail as possible.
* The more information gathered up front, the easier it is to solve
the problem.
* Thank you!

## Configuration Files
Please paste any related configuration files, such as `/etc/rexray/config.yml`
in this section. Please use the appropriate formatting when pasting YAML.
content. For example:

```libstorage:
  # The libstorage.service property directs a libStorage client to direct its
  # requests to the given service by default. It is not used by the server.
  service: efs
  server:
    services:
      efs:
        driver: efs
        efs:
          securityGroups:
          - sg-********
          region:         us-east-1
          tag:            test
          disableSessionCache: false
          statusMaxAttempts:  6
          statusInitialDelay: 1s
          statusTimeout:      2m
```

Proper formatting of pasted content is very important as structured data can
sometimes be accidentally recorded incorrectly, affecting the desired outcome.

## Logs
It is very important when filing an issue to include associated logs. There are
two different logs about which to be concerned: the service log (if REX-Ray is
running as a service) and the client log.

### Service Log
The REX-Ray service log file is stored at `/var/log/rexray/rexray.log`. Instead
of pasting the entire log file into this issue, please create a new
[gist](https://gist.github.com/) and paste the log file's contents there.
Please name the file `rexray-service.log` in the gist. The proper extension will
indicate how to format the contents.

### Client Log
```
DEBU[0002] removing task                                 host=unix:///var/run/rexray/347979462.sock instanceID=efs=subnet-e21f27ce,availabilityZone=us-east-1c&region=us-east-1&securityGroups=sg-26d6a355 removedAfter=0s route=volumesForService server=metal-roar-ng service=efs storageDriver=efs task=0 tasksLen=1 time=1506541670128 tls=false txCR=1506541669 txID=09fd65ac-63cf-4672-626a-690ac48a9409
DEBU[0002] removed task                                  host=unix:///var/run/rexray/347979462.sock instanceID=efs=subnet-e21f27ce,availabilityZone=us-east-1c&region=us-east-1&securityGroups=sg-26d6a355 route=volumesForService server=metal-roar-ng service=efs storageDriver=efs task=0 tasksLen=0 time=1506541670128 tls=false txCR=1506541669 txID=09fd65ac-63cf-4672-626a-690ac48a9409
DEBU[0002] initialized the path cache                    async=true host=unix:///var/run/rexray/347979462.sock integrationDriver=linux osDriver=linux service=efs storageDriver=libstorage time=1506541670145
```

**Comment by clintkitson** [comment]
Can you review from the EFS console whether multiple volumes by the same
name in fact do exist?

**Comment by jicowan** [comment]
I see 1 volume in the EFS console, test/efsvol. I am using the tag `test` in my config.

**Comment by jicowan** [comment]
After restarting the RexRay service, it started to work.  Go figure.
