### ISSUE TITLE
RBD issues when trying to create in Ceph

### ISSUE THREAD

**Issue by nohtyp** [codedellemc/rexray#1052]
# Summary
I am receiving an error message when trying to create a volume in ceph:
ERRO[0002] Error running command                         args=[rbd status --pool cinder-volumes volume-1efd9b8c-a50c-4d67-887e-a8ec86dca8dd --format json] error=exit status 1 host=unix:///var/run/rexray/907258254.sock instanceID=rbd=10.10.10.10 route=volumesForService server=fantasy-fancier-tv service=rbd stderr=rbd: error parsing command 'status'; -h or --help for usage
 
# New Feature
This section is for issues that relate to suggested enhancements or other
ideas that may improve REX-Ray. Please provide as much detail as possible
regarding the idea. This issue will then serve as the means to have a
discussion about your idea!

# Bug Reports
The issue is with the file rexray/libstorage/drivers/storage/rbd/utils/utils.go
In Ceph the status for the volumes does not use status, it currently uses rbd info image-name
rbd info --pool cinder-volumes volume-0a171cdf-5bf5-4f30-9995-7906eda67369 but in the utils.go the command args are as follows: 

args=[rbd status --pool cinder-volumes volume-1efd9b8c-a50c-4d67-887e-a8ec86dca8dd --format json] error=exit status 1 

When I substituted your commands with the following it works as expected:
rbd info --pool cinder-volumes volume-0a171cdf-5bf5-4f30-9995-7906eda67369 --format json
output:  
{"name":"volume-0a171cdf-5bf5-4f30-9995-7906eda67369","size":21474836480,"objects":5120,"order":22,"object_size":4194304,"block_name_prefix":"rbd_data.1819a52ae8944a","format":2,"features":["layering","striping"]}

## Version

```shell
$ rexray version
REX-Ray
-------
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.2
OsArch: Linux-x86_64
Commit: 4c451f856336c83680cc250ff62998bc70876c40
Formed: Tue, 12 Sep 2017 17:18:02 EDT


libStorage
----------
SemVer: 0.4.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a1103d3f215117f7b9f51dae2b24f852c9c54995
Formed: Mon, 23 Jan 2017 10:14:12 EST
```

## Expected Behavior
When I run the command rexray volume create testvol --size 2 it should create a volume in ceph with the desired name and size.

## Actual Behavior
FATA[0000] error creating volume                         error.inner.volumeName=testvol error.inner.driverName=rbd error.inner.opts.Size=2 error.status=500 error.msg=Failed to create new volume volume=testvol

This command works fine when running the command:  rbd create --pool cinder-volumes --size 20480 (which is the size in MB) pg_data1

**Comment by codenrhoden** [comment]
@nohtyp Thanks for the writeup. I'm just about to step away for the day, but one immediate thing I can ask for  is what version of the Ceph utilities are you running?

The output of `ceph --version` is sufficient.

**Comment by nohtyp** [comment]
ceph version 0.87 (c51c8f9d80fa4e0168aa52685b8de40e42758578)

**Comment by codenrhoden** [comment]
Hi @nohtyp,

Thanks for that info.  0.87 maps to Giant, which was officially EOL'd by the Ceph project in April of 2015. In other words, it's really old. :)

The `rbd status` command was added in Infernalis, version `9.2.x`, which was first released in November 2015, almost 2 years ago.  `rbd status` and `rbd info` do provide different types of information. Namely, `rbd status` provides information on which clients have the RBD device attached, which is critical to the operation of REX-Ray, therefore it is required.

If you are not in a position to upgrade your Ceph _cluster_ away from Giant, I do believe it is still possible to upgrade your Ceph _clients_ to at least Infernalis (and probably Luminous, FWIW), as the clients can generally handle talking to older clusters.

I will submit a PR that documents that the minimum Ceph client version is Infernalis, as I see that is missing from the docs. I also recommend staying on versions of Ceph that are [not EOL](http://docs.ceph.com/docs/master/releases/), which right now are Jewel and Luminous.

**Comment by nohtyp** [comment]
Leaving open until documentation is updated.
