### ISSUE TITLE
Unable to use rex-ray with openstck cincer with self-signed certificate

### ISSUE THREAD

**Issue by velislav** [codedellemc/rexray#1062]
# Summary
I am unable to list and create volumes from rex-ray service to openstack cinder. I have a self-signed certificate on openstack horizon. How can ignore the self signed certificate? The error is in the service log file.

## Version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.10.2
OsArch: Linux-x86_64
Commit: 4c451f856336c83680cc250ff62998bc70876c40
Formed: Wed, 13 Sep 2017 00:18:02 EEST

## Expected Behavior
To be able to create volumes.

## Actual Behavior
I am unable to create volumes.

## Steps To Reproduce
1. Start rexray start
2. rexray volume create pg_data --size=1
FATA[0003] error creating volume                         error=Post http://libstorage-server/volumes/cinder: EOF volume=pg_data

## Configuration Files
libstorage:
  # The libstorage.service property directs a libStorage client to direct its
  # requests to the given service by default. It is not used by the server.
  service: cinder
  server:
    services:
      cinder:
        driver: cinder
cinder:
  authUrl: http://10.32.79.5:5000/v3.0/
  userName: user
  password: pass
  tenantName: devs
  domainName: Default
  regionName: RegionOne

### Service Log
https://gist.github.com/velislav/c5a33a93406ff43a8e2cd4e6650d0405

### Client Log
$ rexray volume create pg_data --size=1
FATA[0003] error creating volume                         error=Post http://libstorage-server/volumes/cinder: EOF volume=pg_data

**Comment by clintkitson** [comment]
Hello @velislav,

I don't feel as though this is a complete look at the configuration files since `libstorage-server` is being referenced by I am not seeing that in your configs. Can you review the configs and ensure the issue is complete?

**Comment by velislav** [comment]
Hello @clintkitson,

I do not know where this come from, but my config is this:
https://gist.github.com/velislav/305851fcdc2cd79155eb7cbea9d8df7f
There is not such thing as "libstorage-server" inside.

Do you know where can I change this variable?

**Comment by velislav** [comment]
The problem was with the self signed certificate. I add it to the system store with the following steps (this work on ubuntu):
    1. Get the openstack certificates
    openssl s_client -showcerts -connect example.domain.net:8776 > openstack.crt
    2. Clear the certificate inside openstack.crt
    3. Continue
    mkdir /usr/share/ca-certificates/openstack
    cp openstack.crt /usr/share/ca-certificates/openstack/openstack.crt
    chmod 755 /usr/share/ca-certificates/openstack
    chmod 644 /usr/share/ca-certificates/openstack/openstack.crt
    4. Trust the certificate 
    dpkg-reconfigure ca-certificates 

I am able to create and remove volumes.
