### ISSUE TITLE
Security issue with user credentials deployed on the mesos agent host

### ISSUE THREAD

**Issue by maricaantonacci** [codedellemc/rexray#112]
Putting user's credentials inside the mesos agent in order to configure some storage platforms like EC2, Openstack, etc. can become a security vulnerability in case the host is compromised: the attacker can use the user's credentials and take control of anything the user has permission to access.

**Comment by akutz** [comment]
Hi @clintonskitson,

Is there an alternative to this approach? REX-Ray needs credentials in order to access the services, so I'm not sure what the correct approach is here unless it's fetching credentials from some remote, secure store we create?

**Comment by clintonskitson** [comment]
I see a handful of paths and even combination of strategies to comprehensively tackle this.

1) In case the case of EC2 there may be IAM based authentication that can take place to allow a instance to maintain a role that enables it to have enough rights to satisfy RR without access/secret keys stored locally.
2) Openstack may a similar option via Keystone 
3) RR could be ran as a central service an distributed service.  The distributed side would handle guest discovery, etc. and the central RR would handle control plane calls to storage platforms with creds.
4) Locally encrypt creds using lockbox
5) Pass creds in encrypted string
6) Limit roles and pass creds - Only allow the mount/unmount operations to take place on guests and ensure they include proper auth key

Just throwing some ideas out there for now.

**Comment by akutz** [comment]
Hi @clintonskitson,

Let me rephrase it, I see nothing wrong with what we're doing. It is quite common and the norm for users to store credentials in a protected file or as environment variables on a Linux server. To me this is quite low in priority as it is standard op procedure middleware. There are several opportunities as you have presented, but to me those are good reasons for someone to fork the project and add support for them.

**Comment by clintonskitson** [comment]
@akutz I don't disagree here.  Since there are a ton of options, we need to be discuss and be opinionated to help give direction to anyone wishing to contribute here.

**Comment by akutz** [comment]
Hi @clintonskitson, 

Yep, no worries, we're on the same page. I just don't view it as a security risk as it's par for the course.
