### ISSUE TITLE
required permissions need to documented and error messages more clear

### ISSUE THREAD

**Issue by jaroslavl1** [codedellemc/rexray#122]
For rexray cli to work on amazon you need to have permissions for volume, snapshot operations but also to execute describe instances. The last one is not apparent and you get weird errors like:

core@ip-10-60-130-22 ~ $ rexray volume create --size=1 --volumename="vol4" --volumetype="gp2"
FATA[0000] You are not authorized to perform this operation. (UnauthorizedOperation) 

core@ip-10-60-130-22 ~ $ rexray volume attach --volumeid="vol-c5a56623"
FATA[0000] Error: Driver Instance discovery failed: You are not authorized to perform this operation. (UnauthorizedOperation) 

It would be helpful if the error also contained name of the operation that failed. In the 2nd case it may look like some local configuration issue when its not. In the 1st case it looks like some permission problem but operation is unknown. So for example contain "describe-instances" in error message.

**Comment by clintonskitson** [comment]
@jaroslavl1 In this case the `-l debug` flag would likely assist in further information.  I believe are right though, the EC2 driver could use more verbose information relating to which operations are being called.  We are implementing the `goamz` package so we are somewhat limited on the details that can be exposed.

**Comment by cantbewong** [comment]
It would be nice to document an example or actual set of required permissions. 

Also my observation is that the `-l debug` flag is not helpful when troubleshooting permission issues

This set works for me, but could be granting permissions that go beyond what is actually needed.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1447218584000",
            "Effect": "Allow",
            "Action": [
                "ec2:AttachVolume",
                "ec2:CopySnapshot",
                "ec2:CreateSnapshot",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:DeleteSnapshot",
                "ec2:DeleteVolume",
                "ec2:DescribeInstances",
                "ec2:DescribeKeyPairs",
                "ec2:DescribeSnapshotAttribute",
                "ec2:DescribeSnapshots",
                "ec2:DescribeTags",
                "ec2:DescribeVolumeAttribute",
                "ec2:DescribeVolumeStatus",
                "ec2:DescribeVolumes",
                "ec2:DetachVolume",
                "ec2:EnableVolumeIO",
                "ec2:ImportSnapshot",
                "ec2:ImportVolume",
                "ec2:ModifyInstanceAttribute",
                "ec2:ModifySnapshotAttribute",
                "ec2:ModifyVolumeAttribute",
                "ec2:ResetSnapshotAttribute"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```
