### ISSUE TITLE
Docker reports "Error response from daemon: no such file or directory"

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/rexray#180]
This was seen when trying to run REX-Ray 0.2.1 with Docker 1.8.2 on Fedora Atomic.  If specifying `docker run -ti --volume-driver=rexray  -v test:/test busybox` an error is returned (with debug mode on) as follows.

```
ERRO[0034] Handler for POST /containers/create returned error: no such file or directory 
ERRO[0034] HTTP Error                                    err=no such file or directory statusCode=404
Error response from daemon: no such file or directory
```

This looks to be caused by having SELinux on.  You can edit the `/etc/sysconfig/docker` file and remove the `--selinux-enabled` flag and reset docker with `service docker restart`.

**Comment by miry** [comment]
Is any other solution instead of disable --selinux?

**Comment by clintonskitson** [comment]
@miry Great question.  I am assuming there is a security setting that needs to be flipped to enable the mounts/unmounts that RR is attempting.  Need to research this one.

**Comment by clintonskitson** [comment]
Referencing Docker issue https://github.com/docker/docker/issues/18005

**Comment by HackToday** [comment]
hi @clintonskitson  any in progress for this issue ?  I did not find docker side confirmation what's the root cause for this

**Comment by clintonskitson** [comment]
@HackToday I saw that thread as well. I haven't been able to test it with the patch/ver commit specified. If you get a chance to let us know! It is on the list

**Comment by HackToday** [comment]
hi @clintonskitson  what patch do you think fix the issue ? I did not get it.

**Comment by HackToday** [comment]
I think it is needed fix, the won't fix not make for consumer especially it is security issue

**Comment by rhatdan** [comment]
Where do I get rexray so I can try this out and see what is going on from an SELinux issue?  Is the source available?

**Comment by HackToday** [comment]
hi @rhatdan  I am not sure if familiar with Openstack or EC2. If you have some environment, You could try follow this:

http://rexray.readthedocs.org/en/stable/user-guide/installation/

and 

EC2: http://rexray.readthedocs.org/en/stable/user-guide/storage-providers/ec2/
Openstack: http://rexray.readthedocs.org/en/stable/user-guide/storage-providers/openstack/

I used Openstack. You could also try virtualBox if you have that.

Or if you not have above resource, you could give that logging need to enable and how to enable related selinux logging. And I could try to upload related logs to you under this issue.

Thanks

**Comment by HackToday** [comment]
@rhatdan are you working on this ?

and also @clintonskitson  does coreos have such limitation?  if atomic can not have such issue sovled, we could move to coreos.

But if all have issues, I think it may impact others to adopt rexray. As they think it is criticail security issue.

**Comment by rhatdan** [comment]
@HackToday Please contact me at dwalsh@redhat.com, and we can work this through.

**Comment by raphtheb** [comment]
Currently experiencing this issue first-hand on CoreOS 962.00, Docker 1.10.1 and rexray 0.3.1 . It seems like the issue is not limited to atomic.

**Comment by clintonskitson** [comment]
@raphtheb Have you tried the fix as listed https://github.com/docker/docker/issues/18005

**Comment by raphtheb** [comment]
@clintonskitson That's my next step, will report my findings.

**Comment by HackToday** [comment]
@raphtheb  Thanks for you info, Please let me know your results

**Comment by raphtheb** [comment]
As a follow-up, i have been unable to get the fix mentioned in docker/docker#18005 to help in resolving this issue. That being said, for our current use-case, disabling SELinux isn't too big a deal and will be our preferred solution until a more permanent resolution is achieved.

**Comment by HackToday** [comment]
so @raphtheb  it means you still need to disable selinux for coreos?  

It seems docker/docker#18005  still is open, it is not solved in docker code.

**Comment by clintonskitson** [comment]
Reposting this in our thread, I was able to get around the problem with the following example using CoreOS.

`docker run -ti --security-opt=label:disable --volume-driver=rexray -v testing221:/tst busybox`

**Comment by HackToday** [comment]
Hi @clintonskitson  The point is that nobody would like to add such opts for every containers running.

Consumers would want to 

1) not disable selinux for docker

2)  rexray can run with docker.

**Comment by rhatdan** [comment]
Right disabling SELinux really eliminates one of your primary controls for guaranteeing container separation.

**Comment by HackToday** [comment]
I have confirmed related question in OpenStack community, and @Atomic related person would help to track that .  


But still let's confirm  @clintonskitson according to @rhatdan , https://github.com/docker/docker/issues/18005#issuecomment-190215862

Seems he not hit this issue.  @rhatdan  which atomic version do you use ?  (Atomic 23 or 22 ?)

**Comment by rhatdan** [comment]
Looking at this a little closer, I think we should only call setBindModeIfNull(bind) if we are using the local driver.  Currently this causes 

			if bind.Driver == "local" {
				bind = setBindModeIfNull(bind)
			}
