### ISSUE TITLE
Specifying the --config option does not work when starting REX-Ray as service

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/rexray#193]
If starting RR as a service `rexray start --config=/tmp/file`, the config is not passed to the actual start command causing RR to not start.  Specifying the config file does work however for interactive CLI usage currently.  Due to this bug, the service currently requires that the config file be available in the standard locations.

```
DEBU[0000] invoking service start                        os.Args=[./rexray start --config=/etc/rexray/config.yml.tst -l debug]
Starting REX-Ray...DEBU[0000] trying to start service                       client=/tmp/GtUzDjaxpGiewguFPzeOqREmfPzfYpaY.sock
time="2015-12-02T23:26:13Z" level=debug msg="updated log level" rexrayLogLevel=debug 
time="2015-12-02T23:26:13Z" level=debug msg="invoking service start" os.Args=[/home/ubuntu/rexray start --client=/tmp/GtUzDjaxpGiewguFPzeOqREmfPzfYpaY.sock --rexrayLogLevel=debug --rexrayHost=tcp://:7979]
DEBU[0000] accepted connection                          
DEBU[0000] received data                                
FAILED!
DEBU[0000] exiting with error code 1 
```

**Comment by akutz** [comment]
You know, instead of filing bugs you *could* fix them... Just saying ;) This is low-hanging fruit (I think). I'll take a look later tonight or tomorrow.

**Comment by clintonskitson** [comment]
Yup just my way of taking note for now so we can make sure to check back into it.

**Comment by akutz** [comment]
Cool beans.
