### ISSUE TITLE
Add Volume Manager interface for Kubernetes Volumes functionality

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/rexray#20]
TBD

**Comment by altvnk** [comment]
It would be really cool to have such functionality in Kubernetes! So +1

**Comment by clintonskitson** [comment]
Thanks for the feedback @altvnk!

**Comment by rimusz** [comment]
any updates on Kubernetes integration?

**Comment by clintonskitson** [comment]
See the thread here for libstorage.

https://github.com/emccode/roadmap/issues/133#issuecomment-226937855
