### ISSUE TITLE
non deterministic "no storage drivers initialized" error

### ISSUE THREAD

**Issue by shayts7** [codedellemc/rexray#269]
We use rexray to mount/unmount volumes in our EC2 hosts, sometimes there are cases where rexray throws "no storage driver initialized" error and could not find the existing volume. 

Attached is a log file: [result-upload-service_restart_log.txt](https://github.com/emccode/rexray/files/103771/result-upload-service_restart_log.txt), in lines 11,12, 50 and 51 you can see the log prints indicating that the volume could not be found, it is probably due to the "no storage driver initialized" error that rexray promted, the strange think is that after 30 sec we call again "rexray" but this time everything worked as expected and we could find the volume (lines 60, 61).

It seems there is some kind of temporary problems where running rexray, and "-l debug" not always help here. Maybe you can help with a pinpoint for where to look for the problem?

**rexray versioning info:**
Binary: /opt/bin/rexray
SemVer: 0.2.0
OsArch: Linux-i386
Branch: v0.2.0
Commit: b018a3be05b54a110728d3669213e3d8f65de197
Formed: Wed, 30 Sep 2015 21:28:36 UTC

You can find the mount/unmount scripts we are using here: https://github.com/gaia-adm/volume-tools-amazon/blob/master/gaia-mount.sh and here: https://github.com/gaia-adm/volume-tools-amazon/blob/master/gaia-unmount.sh

Also, as for the installed components, you can find them here: https://github.com/gaia-adm/volume-tools-amazon/blob/master/installer.sh

Thanks in ahead for your help!
Shay

**Comment by clintonskitson** [comment]
@shayts7 Thanks for reaching out.

I agree with your  non-deterministic portion of the storage driver initialization logging that you reference here.  The history behind this, is that we would typically try and initialize all storage drivers and thus did not want to be verbose with the general output of errors during those driver initializations.  The `-l debug` flag is the intended way *currently* to view errors during the process.  

With that said, we have made incremental updates to ensure the logging is better within drivers and at the driver managers.  We are expecting to make a change in 0.4 to further enhance this to get it where we want it.

Speaking specifically to the EC2 driver, I believe you are possibly encountering a timeout (50ms) when asking for the instance identity document.  This actually goes back to our previous driver initialization method (try and do all of them), and not wanting to hang all drivers on an unsuccessful ec2 initialization.

```
        conn, err := net.DialTimeout("tcp", "169.254.169.254:80", 50*time.Millisecond)
	if err != nil {
		return &instanceIdentityDocument{}, fmt.Errorf("Error: %v\n", err)
	}
	defer conn.Close()

	url := "http://169.254.169.254/latest/dynamic/instance-identity/document"
	resp, err := http.Get(url)
	if err != nil {
		return &instanceIdentityDocument{}, fmt.Errorf("Error: %v\n", err)
	}
```

Have you recorded a failure with the `-l debug` flag on?

Quick fix here would be to increase the timeout, and make it a configurable setting.  Beyond that a retry mechanism would help it be more resilient.

As an alternative, you could think about starting REX-Ray as a service `rexray start`.  From there you could interface with the HTTP/JSON API through [dvdcli](https://github.com/emccode/dvdcli).

**Comment by shayts7** [comment]
Thanks for the detailed answer! I will look into it.

**Comment by shayts7** [comment]
How can I increase the timeout? Can you point me out to documentation part that explain that?

Thanks,
Shay

**Comment by clintonskitson** [comment]
Right now it would be a custom build to increase the timeout.  We could add
it to 0.3.2 possibly.  I do believe the timeout should be something
configurable.  But it would be nice to see a log that has debug on to be
certain.

**Comment by shayts7** [comment]
I'll try to reproduce it with "-l debug", If I'll have results I will let you know.
Thanks!

**Comment by miry** [comment]
@shayts7 this should help you https://github.com/emccode/rexray/issues/268#issuecomment-176784073

**Comment by shayts7** [comment]
@miry, thanks for the snippet

**Comment by shayts7** [comment]
Small Update - I still did not have a chance to see the problem reproduced (I have a script that executes "rexray volume get" every 60 sec I was running it for few days now, but no error)

I guess it was a temporary network problem in AWS that caused the problem, this assumption gets stronger as we use fleet to manage our services and the "no storage drive initialized" came out after fleet decided to restart one of our services, and it might that fleet performed that restart due to a network connectivity issues.

**Comment by clintonskitson** [comment]
Got it, thanks for the update @shayts7.

**Comment by akutz** [comment]
Hi @shayts7,

Where's the timeout setting to which you referred? I can make it configurable for our next release (point or otherwise).

**Comment by clintonskitson** [comment]
Here is the line with the timeout https://github.com/emccode/rexray/blob/master/drivers/storage/ec2/ec2.go#L131
