### ISSUE TITLE
EC2: unsupported protocol scheme ""

### ISSUE THREAD

**Issue by byrnedo** [codedellemc/rexray#279]
I keep getting this error for various commands when running on an aws instance. Is the base url screwed up or something??

This happens from the docker side doing `docker volume create --driver rexray --opt size=1 --name test` as well.

```
>$ rexray volume get
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]                                      
INFO[0000] [docker]                                     
INFO[0000] [ec2]                                        
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[ec2] volumeDrivers=[docker]
INFO[0000] os driver initialized                         provider=linux
INFO[0000] volume driver initialized                     provider=docker
INFO[0000] storage driver initialized                    provider=ec2
FATA[0000] Get /?AWSAccessKeyId=XXX&Action=DescribeVolumes&Signature=YYY&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=ZZZ&Version=2015-03-01: unsupported protocol scheme ""
```

My conf looks like this:

```
rexray:
  logLevel: debug
  storageDrivers:
    - ec2
aws:
  accessKey: XXX
  secretKey: YYY
  region: eu-central-1
```

**Comment by clintonskitson** [comment]
Is it an intermittent error or when any commands are requested?

It looks like it is complaining about the API version we are using.

**Comment by byrnedo** [comment]
Happens with any command.
The rexray version by the way: 
```
Binary: /usr/bin/rexray
SemVer: 0.3.1
OsArch: Linux-x86_64
Branch: v0.3.1
Commit: bf4d6eec8c931b10d1ec187de052a23c09681ac6
Formed: Wed, 30 Dec 2015 21:12:44 UTC
```

**Comment by clintonskitson** [comment]
Can you try it in another region?

**Comment by byrnedo** [comment]
yeah, I'll give it a go

**Comment by byrnedo** [comment]
Just FYI, removing the region flag makes no difference. 
I haven't got round to launching in another region yet.

**Comment by clintonskitson** [comment]
Ok.  I am wondering the region you are in does not support some level of
API version by design or possibly unintentionally.

**Comment by byrnedo** [comment]
It worked on us-east-1 no problem.

**Comment by clintonskitson** [comment]
Any chance that there may be SSL problems in the original instance?  Have
you tried from different AMIs in the same region?

**Comment by byrnedo** [comment]
Tried it on a fresh, stock ubuntu ami in eu-central-1 again and no good (
that was the 'same' ami, the amazon standard ubuntu, I tried in us-east-1).
Will try with some other ubuntu amis.

**Comment by byrnedo** [comment]
Ok, tried it on eu-west-1 (Ireland, my homeland to the rescue) and it works!! I'm gonna check my access keys and there permissions but maybe central-1 has limitations.

**Comment by byrnedo** [comment]
Ok, definitely something to do with either that one ami (stock ubuntu, ami-87564feb) or the region doesn't support it. I followed exact same procedure on this as in eu-west-1 and it just doesn't work.
