### ISSUE TITLE
get-volume can see all EBS volumes outside of its AZ

### ISSUE THREAD

**Issue by kacole2** [codedellemc/rexray#28]
when performing a `rexray get-volume` in AWS, it gets all EBS volumes. That becomes a problem because a container cannot mount a volume if it's in a different AZ than the host.

It would be good if rexray only discovered volumes within the AZ the host is in

**Comment by jaroslavl1** [comment]
I prefer the get operation as it works now. It allows you to detect where the volume is located. If you want to get volumes just in a specific AZ, I think there should be an option to select the AZ.

**Comment by clintonskitson** [comment]
I would think that an option to select on AZ and VolumeType would make sense.
