### ISSUE TITLE
Question: Will REX-Ray Support ScaleIO Snapshots

### ISSUE THREAD

**Issue by akamalov** [codedellemc/rexray#345]
Hey Clint, just a question: will REX-Ray Support ScaleIO Snapshots ? For instance, if I want to present a snapshot volume to another container ?

Thanks!!

Alex

**Comment by orioncuba** [comment]
Hi folks
Question from customer can we use rexray in a Openshift broker(kubernetes)+ dockers install
Ann do scaleio snaps. 
Openshift v3
Oscar

**Comment by akamalov** [comment]
Hey Clint,

I stand corrected. It does show. I for some reason assumed that it will be visible under "volume list" and I should have done "snapshot list".

Thanks again!!!

Alex

**Comment by clintonskitson** [comment]
No problem @akamalov. Yeah, the RR volume list gets filtered based on if the ancestorid is filled or not. But to ScaleIO they are all volumes.

**Comment by akamalov** [comment]
Hey Clint, 

Just a small question: Does REX-Ray support "snap-back" or snap-restore feature ? Let's say I took a volume snapshot, later data got corrupted on a primary volume, and I can go ahead and restore data  back onto that volume? Can it be done ?

**Comment by clintonskitson** [comment]
@akamalov That should technically work. We will have to review it and see what is going on for that not to occur.

But today the rollback feature to an existing volume is not supported with REX-Ray. We can also look at globally supporting a rollback feature as it is would be valuable.

**Comment by dvonthenen** [comment]
@akamalov I was able to create a volume from a snap, but the only difference in the command line used for me was to also specify the size (same as the snap). You would think that the size might not be needed since the snap already has size. Give that a try and see if that works for you.

Looks like we need to enhance the create and if a snapid is provided to either copy the size from the snap or if it isnt required, then to remove the restriction.

**Comment by akamalov** [comment]
@dvonthenen Thanks David. Yep, it worked when size is provided. Thanks a lot!

Alex

**Comment by dvonthenen** [comment]
Good to hear. Will take a look at simplifying the usability so that size doesn't need to be specified.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/libstorage #457](https://github.com/codedellemc/libstorage/issues/457) via [**ZenHub**](https://www.zenhub.com/)
