### ISSUE TITLE
REX-Ray only supports commercial storage as a docker storage?

### ISSUE THREAD

**Issue by zhaijunming** [codedellemc/rexray#348]
REX-Ray only supports commercial storage as a docker storage?

**Comment by clintonskitson** [comment]
@zhaijunming REX-Ray supports any storage platform to which there is a driver. Have you reviewed the drivers that are available? GCE, AWS, OpenStack, VirtualBox, ScaleIO, VMAX, XtremIO, Isilon.

**Comment by zhaijunming** [comment]
How to use the VirtualBox test?
With VirtualBox installed centos7, and then in the centos7 system test?

**Comment by greatbn** [comment]
@zhaijunming  please find in docs directory
link: https://github.com/emccode/rexray/blob/master/.docs/user-guide/storage-providers.md#virtualbox

**Comment by clintonskitson** [comment]
Thanks @greatbn. Also see blog posts we have done https://blog.emccode.com/2016/01/19/volume-plugins-with-docker-toolbox-and-boot2docker/

**Comment by codenrhoden** [comment]
Can this issue be closed now?
