### ISSUE TITLE
docker-compose volume name on GCE

### ISSUE THREAD

**Issue by sterling312** [codedellemc/rexray#349]
When creating a rexray volume with docker-compose, the compose will automatically add project name in front of the volume name (default to the folder name of where the compose file is) separated with underscore. 

GCE volumes does not accept underscore as valid volume name. Most likely, rexray gce driver will need to transpose any _ to something safe like - when creating the actual volume name on GCE.

**Comment by codenrhoden** [comment]
Issue moved to [codedellemc/libstorage #458](https://github.com/codedellemc/libstorage/issues/458) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jamespedwards42** [comment]
@codenrhoden @sterling312 Where you able to find a solution to this?  The linked issue above directs to a 404.

**Comment by rimoore** [comment]
I am having the same problem with the s3fs.
