### ISSUE TITLE
Leverage as imported package

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/rexray#35]
It is important to be able to import the RR package in the future.  This may cause friction compared to the single instance daemon mode that has been introduced in 0.2.  To allow this the following can be done today.  Let's make sure that we either set a permanent abstraction between CLI accessing RR and packages importing RR and provide similar functionality re consuming configuration files.

```
import rexray "github.com/emccode/rexray/rexray/commands"

rexray.UpdateLogLevel()
rexray.InitDriverManagers()
sdm := rexray.GetSdm()
```

**Comment by akutz** [comment]
Great points @clintonskitson. What's more is the fact that REX-ray doesn't really want to compile without the Makefile because we use LDFLAGS to inject version information that can cause panics if lacking during certain executions...
