### ISSUE TITLE
Azure storage support

### ISSUE THREAD

**Issue by frank-montyne** [codedellemc/rexray#361]
Hi,

Any chance of seeing support for Azure (page blob) storage in the future?

Thanks,
Frank

**Comment by clintonskitson** [comment]
I believe if you're referring to standard or premium disks then it could very well be a target. We are definitely opening to seeing a contribution of an azure driver here.

**Comment by frank-montyne** [comment]
Yes that's what I meant.

**Comment by jeacott** [comment]
+1

**Comment by wondenge** [comment]
This would be great addition to the community.

**Comment by Radek44** [comment]
Was wondering if there was anyone working on this?
I would be interested in having a look into this feature - where can I find the drivers for the other platforms for inspiration about what is needed?

**Comment by codenrhoden** [comment]
@Radek44 I'm not aware of anyone working on Azure at the moment.

All storage provider drivers are here: https://github.com/emccode/libstorage/tree/master/drivers/storage

Thanks for taking a look!

**Comment by kacole2** [comment]
@Radek44 no one is working from the {code} team on it.  We talked to some people from Microsoft at container con in Toronto and they were interested in looking to build a driver. However, nothing has come out of fruition from those initial discussions. We are more than happy to have somebody contribute the driver. Look at the other drivers as a reference model. If you have any questions,  create an issue in the libStorage repo and we can get you sorted out.

**Comment by gfilicetti** [comment]
+1 on Azure storage support, please listen MSFT team!
