### ISSUE TITLE
Containerize rexray

### ISSUE THREAD

**Issue by aluzzardi** [codedellemc/rexray#385]
There have already been efforts to document the process (#347), but it would be great if there was an official image readily available for rexray as it would greatly simplify the automation process.

**Comment by clintonskitson** [comment]
@aluzzardi There was a PR introduced by @wlan0 for this https://github.com/emccode/rexray/pull/347

I am supportive of providing releases to Docker Hub. What we are really missing to formally go this direction is clear directions for all of RR's drivers being ran from inside a container. 

Each driver includes it's own requirements on access to certain things like devices and introspection tools. This causes the `-v` mappings to differ depending on which drivers are being launched.

**Comment by aluzzardi** [comment]
Would it be possible to do something like [cAdvisor](https://github.com/google/cadvisor), which basically mounts pretty much the entire host system in the container?

It doesn't seem shocking to me if RR requires a bunch of mounts from the host.

**Comment by clintonskitson** [comment]
The problem is that RR and its drivers are looking for specific tools and
devices etc in the / path and not a sub path as you would do when mounting
the complete / from the host. Good idea though, having a prefix setting
that was respected for all of the drivers would make it so you could more
easily just specify the whole host to a specific directory in the container
and then point the drivers to use tha sub path.

**Comment by aluzzardi** [comment]
@clintonskitson A prefix setting would be awesome.

Do you think this could be a multistep process, where first we get an official RR image published somewhere and let people fiddle with the right `-v` settings and then eventually we handle prefixes?

**Comment by clintonskitson** [comment]
@aluzzardi I would see it as one step where we have a PR with a Dockefile and it is linked to Docker Hub at that point. It should also come with good instructions on how it can be used including the feature I suggested.

For now there is a Dockerfile that is shown in the PR that currently exists for containerizing done by folks at Rancher.
