### ISSUE TITLE
Rexray failure to initialize scaleio driver on Ubuntu - latest 0.3.3rc1

### ISSUE THREAD

**Issue by clubanderson** [codedellemc/rexray#386]
When I attempt to use the new rexray binary from https://bintray.com/artifact/download/emccode/rexray/staged/latest/rexray-latest-x86_64.deb

On ubuntu:

root@css-c-sdlc-021:/opt# rexray volume list -l debug
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]  
INFO[0000] [docker]  
INFO[0000] [scaleio]  
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[scaleio] volumeDrivers=[docker]
DEBU[0000] error initializing driver                     driverName=ScaleIO error.useCerts=false error.apiVersion= error.provider=ScaleIO error.moduleName= error.endpoint="https://10.202.46.31/api" error.insecure=true
INFO[0000] os driver initialized                         moduleName= provider=linux
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName= provider=docker size= volumeRootPath=/data volumeType=
DEBU[0000] checking volume path cache setting            pathCache=false
Oops, an error occured!

  no storage drivers initialized

And in the api log:

10.202.46.30 - - [21/04/2016:14:58:43 +0000] "GET /api/login HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:58:43 +0000] "GET /api/version HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:58:43 +0000] "GET /api/types/System/instances HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:58:43 +0000] "GET /api/instances/System::3e2f5b62112e6f70/relationships/ProtectionDomain HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:58:43 +0000] "GET /api/instances/ProtectionDomain::b395321100000000/relationships/StoragePool HTTP/1.1" 200 -

With the code on RHEL:
I get the following successful return:

[root@css-c-sdlc-021 ~]# rexray volume ls -l debug
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]  
INFO[0000] [docker]  
INFO[0000] [scaleio]  
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[scaleio] volumeDrivers=[docker]
INFO[0000] os driver initialized                         moduleName= provider=linux
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName= provider=docker size= volumeRootPath=/data volumeType=
INFO[0000] storage driver initialized                    endpoint=https://10.202.46.31/api insecure=true moduleName= provider=ScaleIO useCerts=false
DEBU[0000] checking volume path cache setting            pathCache=false
INFO[0000] sdm.GetVolume                                 driverName=ScaleIO moduleName= volumeID= volumeName=

on the gateway I see (API log)(Success):

10.202.46.30 - - [21/04/2016:14:54:08 +0000] "GET /api/login HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:54:08 +0000] "GET /api/version HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:54:08 +0000] "GET /api/types/System/instances HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:54:08 +0000] "GET /api/instances/System::3e2f5b62112e6f70/relationships/ProtectionDomain HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:54:08 +0000] "GET /api/instances/ProtectionDomain::b395321100000000/relationships/StoragePool HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:54:08 +0000] "GET /api/instances/System::3e2f5b62112e6f70/relationships/Sdc HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:54:08 +0000] "GET /api/types/StoragePool/instances HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:54:08 +0000] "GET /api/instances/System::3e2f5b62112e6f70/relationships/ProtectionDomain HTTP/1.1" 200 -
10.202.46.30 - - [21/04/2016:14:54:08 +0000] "GET /api/types/Volume/instances HTTP/1.1" 200 -

It appears that on ubuntu the api fails just after getting storagepool relationships api call, because the api calls continue in the log for rhel correctly..

**Comment by clintonskitson** [comment]
It is trying to retrieve the local sdc guid and failing.

https://github.com/emccode/goscaleio/blob/5b02f78c9e4b331a05271145196c15c6614b9eff/sdc.go#L126-L140

Can you run this command successfuly?
`/opt/emc/scaleio/sdc/bin/drv_cfg --query_guid`

It is likely that the SDC isn't configured correctly?

**Comment by clintonskitson** [comment]
Following this command is the last step of initialization where we verify that SDC can be seen from the gateway that RR that talk with.

**Comment by clubanderson** [comment]
[root@css-c-sdlc-021 ~]# /opt/emc/scaleio/sdc/bin/drv_cfg --query_guid
2785B5FB-C3B0-400E-8D73-77A93BA3C0F1


The docker host (RHEL) is where I ran the above command.  It succeeded.  The ubuntu container does not have any scaleio components installed on it and therefore I could not run the command there.

Both the docker host and the container are both pointed (via rexray config) to the same gateway with the same settings.

[root@css-c-sdlc-021 ~]# more /etc/rexray/config.yml 
rexray:
  storageDrivers:
  - scaleio
scaleio:
  endpoint: https://10.202.46.31/api
  insecure: true
  userName: admin
  password: Cluster1!
  systemName: atg1
  protectionDomainName: protection_domain1
  storagePoolName: pool1

**Comment by clintonskitson** [comment]
Not sure if I follow what your are trying to do?

Are you running RR inside of a container?

The instance where RR is running needs a valid and configured SDC installed
if you want storage to be add available to that instance.

**Comment by clubanderson** [comment]
SDC is now installed and scini is running

root@css-c-sdlc-021:/var/tmp# dpkg -i EMC-ScaleIO-sdc-2.0-5014.0.Ubuntu.14.04.x86_64.deb 
Selecting previously unselected package emc-scaleio-sdc.
(Reading database ... 29538 files and directories currently installed.)
Preparing to unpack EMC-ScaleIO-sdc-2.0-5014.0.Ubuntu.14.04.x86_64.deb ...
Unpacking emc-scaleio-sdc (2.0-5014.0.Ubuntu.14.04) ...
Setting up emc-scaleio-sdc (2.0-5014.0.Ubuntu.14.04) ...
update-rc.d: warning: default start runlevel arguments (2 3 4 5) do not match scini Default-Start values (2 3 5)
 System start/stop links for /etc/init.d/scini already exist.
 * 

Processing triggers for ureadahead (0.100.0-16) ...
root@css-c-sdlc-021:/var/tmp# service scini status
scini driver is running
root@css-c-sdlc-021:/var/tmp# rexray volume ls -l debug
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]                                      
INFO[0000] [docker]                                     
INFO[0000] [scaleio]                                    
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[scaleio] volumeDrivers=[docker]
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName= provider=docker size= volumeRootPath=/data volumeType=
INFO[0000] os driver initialized                         moduleName= provider=linux
DEBU[0000] error initializing driver                     driverName=ScaleIO error.insecure=true error.provider=ScaleIO error.useCerts=false error.apiVersion= error.moduleName= error.endpoint="https://10.202.46.31/api"
DEBU[0000] checking volume path cache setting            pathCache=false
Oops, an error occured!

  no storage drivers initialized


Same errors in rexray command and same results in API log on gateway

I had to upgrade linux kernel to 4.2 from 3.3 to get the SDC to install.

**Comment by clintonskitson** [comment]
How about the query guid command?

Did u do a MDM_IP= when you installed the SDC?

**Comment by clubanderson** [comment]
Ahh. You mean that's important?  Whoops. Let me try that next.

**Comment by clubanderson** [comment]
No good

root@css-c-sdlc-021:/var/tmp# export MDM_IP="10.202.46.31,10.202.46.30"
root@css-c-sdlc-021:/var/tmp# dpkg -i EMC-ScaleIO-sdc-2.0-5014.0.Ubuntu.14.04.x86_64.deb 
Selecting previously unselected package emc-scaleio-sdc.
(Reading database ... 29538 files and directories currently installed.)
Preparing to unpack EMC-ScaleIO-sdc-2.0-5014.0.Ubuntu.14.04.x86_64.deb ...
Unpacking emc-scaleio-sdc (2.0-5014.0.Ubuntu.14.04) ...
Setting up emc-scaleio-sdc (2.0-5014.0.Ubuntu.14.04) ...
Updating file /bin/emc/scaleio/drv_cfg.txt with MDM (10.202.46.31,10.202.46.30)
update-rc.d: warning: default start runlevel arguments (2 3 4 5) do not match scini Default-Start values (2 3 5)
 System start/stop links for /etc/init.d/scini already exist.
 * 

Processing triggers for ureadahead (0.100.0-16) ...
root@css-c-sdlc-021:/var/tmp# service scini status
scini driver is running
root@css-c-sdlc-021:/var/tmp# rexray volume ls -l debug
DEBU[0000] updated log level                             logLevel=debug
INFO[0000] [linux]                                      
INFO[0000] [docker]                                     
INFO[0000] [scaleio]                                    
DEBU[0000] core get drivers                              osDrivers=[linux] storageDrivers=[scaleio] volumeDrivers=[docker]
INFO[0000] docker volume driver initialized              availabilityZone= iops= moduleName= provider=docker size= volumeRootPath=/data volumeType=
INFO[0000] os driver initialized                         moduleName= provider=linux
DEBU[0000] error initializing driver                     driverName=ScaleIO error.useCerts=false error.provider=ScaleIO error.apiVersion= error.moduleName= error.endpoint="https://10.202.46.31/api" error.insecure=true
DEBU[0000] checking volume path cache setting            pathCache=false
Oops, an error occured!

  no storage drivers initialized

**Comment by clintonskitson** [comment]
Check the drv_cfg command, see if you can find the guid from it in the
scaleio system.

**Comment by clubanderson** [comment]
somehow i messed up the docker host now....

[root@css-c-sdlc-021 bin]# ./drv_cfg --query_guid
open kernel device /dev/scini: No such device or address
[root@css-c-sdlc-021 bin]# ls -alrt /dev/scini
crw-r--r--. 1 root root 247, 0 Apr 18 17:57 /dev/scini
[root@css-c-sdlc-021 bin]# 

states that there is no device, when indeed it exists.  the same output comes from inside the docker container.  I have removed and reinstalled the SDC and it still fails.  I have restarted the scini service as well.

[root@css-c-sdlc-021 bin]# service scini status
scini driver is running

output of the other SDC's in the cluster returns a proper GUID.

**Comment by clubanderson** [comment]
Any ideas on what I can try here @clintonskitson ?

**Comment by clubanderson** [comment]
help?

**Comment by chuckchiam** [comment]
FYI, there is a community forum at https://community.emc.com/community/products/scaleio with a lot of  infrastructure minded folks (including people from ScaleIO engineering) that can help to answer these nuts and bolts type of questions.  It will always be the quickest way for you to get an answer around something like what your experiencing, which is smack in the middle of product configuration, whereas Clinton and team are more focused on the code they contribute.

with that said, i do have a few ideas. 

I've attached the output to the items below from a working ubuntu configuration so you have something to reference
[restart-dmesg.txt](https://github.com/emccode/rexray/files/234925/restart-dmesg.txt)

can you post contents of:
/bin/emc/scaleio/drv_cfg.txt 

as well as the output of the following two commands:
/etc/init.d/scini stop
/etc/init.d/scini start

if you can also grab me the output of dmesg when the stop\start is happening that may help as well.

**Comment by clintonskitson** [comment]
@clubanderson Were you able to resolve this?

**Comment by clubanderson** [comment]
No. We didn't. We are looking at solidfire now. But that still requires rexray. Maybe we will revisit it soon. 

Andy

**Comment by clintonskitson** [comment]
Ok, just wanted to give a few lines if you were also inclined to try it again. I use the following to install the SDC client on Ubuntu nodes with no issues like what you mentioned.

```
apt-get install -y unzip install linux-image-4.2.0-30-generic linux-headers-4.2.0-30-generic
unzip /vagrant/ScaleIO_2.0.0_UBUNTU_14.04_Download.zip
cd ScaleIO_2.0.0_UBUNTU_14.04_Download/
tar -xvf EMC-ScaleIO-sdc-2.0-5014.0.Ubuntu.14.04.x86_64.tar 
./siob_extract EMC-ScaleIO-sdc-2.0-5014.0.Ubuntu.14.04.x86_64.siob
MDM_IP=mdm_ip1,mdm_ip2 dpkg -i EMC-ScaleIO-sdc-2.0-5014.0.Ubuntu.14.04.x86_64.deb
```

**Comment by clubanderson** [comment]
The problem was trying to get this to install as part of mesos containerization. With mesos being inside a container itself. 

Andy

**Comment by clintonskitson** [comment]
Yes that can present another challenging level. Can we close this issue or is there anything we can help with on followup?
