### ISSUE TITLE
EBS Encryption

### ISSUE THREAD

**Issue by LudicrousSpeed** [codedellemc/rexray#394]
Is this possible to default to true. We would like to have all of our volumes encrypted.

**Comment by clintonskitson** [comment]
Not currently. This has been requested before and in the most recent release we started using the AWS SDK directly which enables this functionality. I would be open for this functionality and encryption performed by the storage platforms as a configurable option.

**Comment by clintonskitson** [comment]
@LudicrousSpeed By the way, I believe it would be a single option applied to this section of code.

https://github.com/emccode/rexray/blob/master/drivers/storage/ec2/ec2.go#L517-L522

**Comment by LudicrousSpeed** [comment]
Thanks I just added that as we always want our data encrypted.

Much appreciated.
