### ISSUE TITLE
Build issues?

### ISSUE THREAD

**Issue by LudicrousSpeed** [codedellemc/rexray#395]
Running the following

SRC=$(mktemp -d 2> /dev/null || mktemp -d -t rexray 2> /dev/null) && cd $SRC && docker run --rm -it -e GO15VENDOREXPERIMENT=1 -v $SRC:/usr/src/rexray -w /usr/src/rexray golang:1.5.1 bash -c "git clone https://github.com/emccode/rexray.git -b master . && make build-all"

I see the error 

...building rexray Darwin-x86_64...vendor/github.com/spf13/viper/viper.go:39:2: cannot find package "gopkg.in/fsnotify.v1" in any of:
    /go/src/github.com/emccode/rexray/vendor/gopkg.in/fsnotify.v1 (vendor tree)
    /usr/local/go/src/gopkg.in/fsnotify.v1 (from $GOROOT)
    /go/src/gopkg.in/fsnotify.v1 (from $GOPATH)

This is on OSX. Anyone else seeing this issue?

**Comment by LudicrousSpeed** [comment]
I am also seeing an issue when building locally on my mac book pro.

vendor/github.com/emccode/govmax/api/v1/vmomi.go:219: storageSystem.RescanAllHba undefined (type *object.HostStorageSystem has no field or method RescanAllHba)

**Comment by LudicrousSpeed** [comment]
It looks like the second one is an error with the vmomi package https://github.com/emccode/govmax/issues/4

**Comment by clintonskitson** [comment]
@LudicrousSpeed I just ran the same test as you and am encountering the same error. I will investigate further. Thank you for filing the issue.

**Comment by clintonskitson** [comment]
@LudicrousSpeed Can you give the following command a try?

`SRC=$(mktemp -d 2> /dev/null || mktemp -d -t rexray 2> /dev/null) && cd $SRC && docker run --rm -it -e GO15VENDOREXPERIMENT=1 -v $SRC:/usr/src/rexray -w /usr/src/rexray golang:1.5.1 bash -c "git clone https://github.com/emccode/rexray.git -b master . && make build-all"`

**Comment by clintonskitson** [comment]
@LudicrousSpeed Repost.. can you give the following command a try?
```
SRC=$(mktemp -d 2> /dev/null || mktemp -d -t rexray 2> /dev/null) && cd $SRC && docker run --rm -it -v $SRC:/go/src/gith
ub.com/emccode/rexray -w /go/src/github.com/emccode/rexray golang:1.5.1 bash -c "git clone https://github.com/emccode/rexray.git -b master . && make build-all
"
```

**Comment by clintonskitson** [comment]
I believe the command we had before for building was failing to properly download dependencies.

**Comment by LudicrousSpeed** [comment]
I tried the command you have above and am still seeing an issue.

...building rexray Linux-i386...vendor/github.com/spf13/viper/util.go:25:2: no buildable Go source files in /go/src/github.com/emccode/rexray/vendor/github.com/magiconair/properties

**Comment by clintonskitson** [comment]
Interesting. Did the build actually succeed at the end? Any chance network
flakiness could be occurring? Is this running from in VirtualBox on docker
machine?

**Comment by LudicrousSpeed** [comment]
I cannot get it to finish.

OSX yosemite 10.10.5 running docker machine with docker 1.9.1

I will look a little deeper in a little bit.

**Comment by clintonskitson** [comment]
The build process because of storage package dependencies is pretty substantial. This command should be close to what you need for a bigger VM. The good thing on our side is that we do builds with each commit from Travis-CI, so we know that the build process does work from scratch on clean systems with good network connectivity. The example though as we discussed was not up to date which was causing your initial errors.

`docker-machine create --driver=virtualbox --virtualbox-cpu-count=4 --virtualbox-memory=4096 buildsystem`

The build process though is pretty straightforward on OS X as well since it cross-compiles for you. I personally do this for all of my builds.

http://rexray.readthedocs.io/en/stable/dev-guide/build-reference/#build-requirements

**Comment by clintonskitson** [comment]
@LudicrousSpeed I spent some more troubleshooting this and I believe I found the issue. There was a `&` which should have been '\&` which may be the culprit.

Let us know if the new build command works after editing the Makefile. Thanks!
https://github.com/emccode/rexray/blob/ff0358301aecb24cba1894fd109bd40821a55d6c/Makefile#L7

https://github.com/emccode/rexray/pull/398

**Comment by LudicrousSpeed** [comment]
Tried building again tonight with a docker machine created per your specs. Still seeing issues.

  ...building rexray Linux-x86_64...# github.com/emccode/rexray/vendor/github.com/emccode/libstorage/api/client
vendor/github.com/emccode/libstorage/api/client/client_http.go:75: undefined: http.MethodHead
Makefile:228: recipe for target 'build_' failed
make[1]: *** [build_] Error 2
Makefile:283: recipe for target 'build-linux-amd64_' failed
make: *** [build-linux-amd64_] Error 2
make: Target 'build-all' not remade because of errors.
bash-3.2$ docker-machine ls
NAME          ACTIVE   DRIVER       STATE     URL                         SWARM
buildsystem   *        virtualbox   Running   tcp://192.168.99.101:2376

**Comment by clintonskitson** [comment]
You're actually pulling in tip of master there on the 0.4.0 build which is
beubg worked on. If you reset to he v0.3.3 tag before building you should
be good.

**Comment by clintonskitson** [comment]
@LudicrousSpeed Did you get through your build problems?

**Comment by LudicrousSpeed** [comment]
I finally got the 0.3.3 tag to build. However I think it is not right, cause when I deployed it I got a not executable. Then before I headed out of town I could no longer build 0.3.3. I have not been successful with master yet...

I will hopefully have time tomorrow to look at this again.

Thanks!

**Comment by LudicrousSpeed** [comment]
Sorry to be more clear the not executable was not a chmod thing it was like the bin was not an actual functioning binary. I am certain I pulled the x64 and that was what it was running on.

**Comment by clintonskitson** [comment]
You could try a `make` by itself to build more executables. The one I specified is if you're on an x86_64 architecture. This would cause issues if you were trying to use it on OSX, etc.

**Comment by LudicrousSpeed** [comment]
So my coworkers fixed the problem when I was out.

They added two things

make clean and then make only the version we need by specifying make build-linux-and64

Thanks for all of your help!

**Comment by clintonskitson** [comment]
Great, is there anything we can do for the documentation that may help others here? The fix that I mentioned is already committed for the race condition you were initially experiencing.

**Comment by akutz** [comment]
Hi @LudicrousSpeed,

Just so you know, the build process has been greatly enhanced to try and make things far speedier and more elegant. This was the first Makefile I ever wrote by hand -- usually using the autoconf suite. I've updated the Makefile to actually be, well, a Makefile, instead of what was basically a glorified script. I hope this helps! :)
