### ISSUE TITLE
Rexray out of sync if EBS volume removed externally

### ISSUE THREAD

**Issue by jvanns** [codedellemc/rexray#397]
Version/release: 0.3.3-1 on Ubuntu 14.04 LTS

This is quite simple (assume EBS backend storage):

1) docker create volume -d rexray --name=foobar --opt=size=1
Now delete the EBS volume via the AWS CLI or console

2) docker volume ls | grep foobar
Volume is absent

3) docker create volume -d rexray --name=foobar --opt=size=1
Volume is not recreated through command succeeds and returns zero

This does not happen if the volume is removed via rexray/docker.

**Comment by clintonskitson** [comment]
What version of docker is this? I believe this is a known issue prior to
Docker 1.10.

**Comment by jvanns** [comment]
Docker 1.11.0 ;)

**Comment by clintonskitson** [comment]
Can you try and use the disablecache option?

**Comment by clintonskitson** [comment]
Also this could be related to another docker issue. Are all containers that
used the volume completely removed? Even though volumes aren't listed
docker may be holding onto the volume due to the container requiring it
still being present.

**Comment by jvanns** [comment]
Yes, all containers that used the volume are removed - I checked that before (but didn't mention it). I'll try the disable cache option.

**Comment by clintonskitson** [comment]
Doing a full clean on all containers is a good bet just in case, if u can
remove all containers that is.

docker rm -f $(docker ps -qa)

**Comment by jvanns** [comment]
To be clear; there are no running or stopped containers left on the same host.

**Comment by clintonskitson** [comment]
Thanks.

Try and enable logging as well from RR.

rexray:
  logLevel: debug

This will describe all of the activities taking place.

**Comment by jvanns** [comment]
It appears this doesn't happen when using the 'rexray' CLI - only via docker. Here is the output of;

docker volume create -d rexray --name foobar -o size=1

After a delete of an EBS volume of the same name through the console

time="2016-04-29T16:20:50Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=foobar 
time="2016-04-29T16:20:50Z" level=info msg="getting path to volume" driverName=docker moduleName=default-docker volumeID= volumeName=foobar 
time="2016-04-29T16:20:50Z" level=info msg=sdm.GetVolume driverName=ec2 moduleName=default-docker volumeID= volumeName=foobar 
time="2016-04-29T16:20:50Z" level=error msg="/VolumeDriver.Path: error returning path" error="No volumes returned by name" 
time="2016-04-29T16:20:50Z" level=error msg="No volumes returned by name" 

I don't think that helps much! Looks like rexray might be doing the right thing but docker isn't?

**Comment by clintonskitson** [comment]
1) Stop and remove your containers
2) `sudo rexray stop`
3) `sudo rexray start -f -l debug` (in it's own terminal possibly)
4) Simulate your scenario and watch the events that come through RR

Does Docker request a `/VolumeDriver.Create` from us when you do the `docker volume create`?

**Comment by clintonskitson** [comment]
@jvanns Any more information here?

**Comment by jvanns** [comment]
Hi Clinton. Sorry, my efforts were shifted elsewhere. I'll see if I can find time today to reproduce the problem again following your steps.

Jim
