### ISSUE TITLE
cpu usage is 100%

### ISSUE THREAD

**Issue by James-Dao** [codedellemc/rexray#426]
sometimes, cpu usage of rexray will use 100%, at this time , "rexray status" shows that rexray is not running and can not start it with "rexray start".  I want to kill the process, but it fails,  i must force outage.

**Comment by kacole2** [comment]
@James-Dao for us to properly assist, can you provide the following information:
 - Environment (AWS, vSphere)
 - OS Type and Version
 - Linux Kernel Version
 - Docker Version
 - REX-Ray Version
 - logging output from `rexray service start -l debug`

**Comment by James-Dao** [comment]
I will paste the log when running into it next time
