### ISSUE TITLE
rexray volume create command equivalent of aws ec2

### ISSUE THREAD

**Issue by gufranmmu** [codedellemc/rexray#433]
Hi,

What would be the rexray volume create/new command equivalent of the following aws ec2 command?

```
aws ec2 create-volume --size 10 --region eucalyptus --availability-zone esclor86_3 --volume-type standard

output:
{
    "AvailabilityZone": "esclor86_3",
    "Attachments": [],
    "Tags": [],
    "VolumeType": "standard",
    "VolumeId": "vol-94c3707c",
    "State": "creating",
    "CreateTime": "2016-05-15T12:50:03.675Z",
    "Size": 10
}

```

I am able to see the above created volume with rexray volume get --volumeid=vol-94c3707c:

```
- name: ""
  volumeid: vol-94c3707c
  availabilityzone: esclor86_3
  status: available
  volumetype: standard
  iops: 0
  size: "10"
  networkname: ""
  attachments: []
```

How to create a volume with rex-ray command? Thanks for the help!

**Comment by gufranmmu** [comment]
``` 
rexray volume create --size=1 --volumename="rexray-volume" --availabilityzone="esclor86_3" --iops=0 --volumetype="standard"

```
This command gives me the following error:

```
INFO[0000] storage driver initialized                    accessKey=AKIAAGCJ3W3KZ moduleName= provider=ec2 secretKey=HJZ7aLnmezFwcGm3ILV5LIM1TE           R2o6bAmyA
DEBU[0000] checking volume path cache setting            pathCache=false
INFO[0000] sdm.CreateVolume                              IOPS=0 availabilityZone=esclor86_3 driverName=ec2 moduleName= runAsync=false size=1 snapshotID= v           olumeID= volumeName=rexray-volume volumeType=standard
FATA[0000] InvalidInstanceID.Malformed: Invalid id: ""
        status code: 400, request id: 7693c2a5-b7cc-4f12-93b8-d1b90ea602df

```

**Comment by gufranmmu** [comment]
I think the function ``` createVolume() ``` first checks if the instance is already available and returns error based on that.

Got it working by removing this part```if server, err = d.getInstance(); err != nil {``` in ec2.go

I hope this helps rechecking ec2.go for the upcoming release. This might help setting up eucalyptus on single machine and testing: https://www.youtube.com/watch?v=AsIRAKNQMGc

Thank you!
:

**Comment by clintonskitson** [comment]
@gufranmmu Thanks for the info. The getInstance() is critical during certain operations like mount and attach. It is complaining because the introspection is returning no instance ID. 

https://github.com/emccode/rexray/blob/b30fb870b5b94cd8368824460ad020bfcf20be3a/drivers/storage/ec2/ec2.go#L161-L188

Specifically `http://169.254.169.254/latest/dynamic/instance-identity/document` should return a document that includes the InstanceID. If not, then alternate means need to be found or the instanceID must be configured manually per RR instance.

**Comment by gufranmmu** [comment]
Thank you! In eucalyptus, the path  ```` "dynamic/instance-identity/document" ```` returns nothing although HTTP status is 200 so instance-identity document was returning JSON parsing error. However, this is working:
```
user-data[root@mesos-slave-1 ~]# curl  http://169.254.169.254/latest/meta-data
ami-id
ami-launch-index
ami-manifest-path
block-device-mapping/
hostname
instance-id
instance-type
local-hostname
local-ipv4
mac
placement/
public-hostname
public-ipv4
public-keys/
reservation-id
```
So, when enhancing ec2.go, maybe instead of using the "dynamic" path, using the latest would be compatible for both aws EBS and eucalyptus aws EBS.

One more comment regarding the endpoint url. I was testing convoy ( https://github.com/rancher/convoy ) It was able to connect to aws create/mount/umount with docker 
when i added endpoint url in ``` vendor/github.com/aws/aws-sdk-go/private/endpoints/endpoints_map.go ```

Can we expect eucalyptus support in the coming release? When is the release coming? Thanks a lot!

**Comment by clintonskitson** [comment]
@gufranmmu Are you saying that `curl  http://169.254.169.254/latest/meta-data/instance-id` would be the right tag for look at?

It is likely that 0.4.1 will include the updated EC2 driver which would be due out in a couple of weeks.

The REX-Ray project leverages vendoring to ensure the dependent code isn't in the same code base. For REX-Ray, [libstorage](https://github.com/emccode/libstorage) is where the drivers live. This project can be easily added toy our IDE for a simple search as well.
