### ISSUE TITLE
Rex-Ray multi host, same volume

### ISSUE THREAD

**Issue by gufranmmu** [codedellemc/rexray#436]
I wasn't able to test this out, but i think it's easier to ask you guys to get a quick answer :)

Okay, so let's say I execute one docker container  with an EBS volume in host1:

```
sudo docker run -d -v testvol:/testvolume --volume-driver=rexray ubuntu sh -c 'while true; do echo hello > /testvolume/testfile; sleep 2; done;'
```

I kill the docker container and execute the same command as above in host 2. Shall it auto attach and mount that same volume in host2 or it creates a new volume?

The reason why I am asking this is that I tested the same scenarios for convoy, and it creates new volume in each host :(

Current Rex-Ray metadata fetching is not compatible with eucalyptus. The aws feature of dynamic meta-data will be available in 4.3 eucalyptus release.
https://eucalyptus.atlassian.net/browse/EUCA-5601

Thanks in advance for the answer!

**Comment by kacole2** [comment]
@gufranmmu your assumption is correct that REX-Ray will attach the same volume on host2.

**Comment by kacole2** [comment]
@gufranmmu if your question is solved can you please close the issue? thanks!
