### ISSUE TITLE
rexray on openstack 

### ISSUE THREAD

**Issue by rahuldivgan** [codedellemc/rexray#485]
Getting the following error even after providing the config file at /etc/rexray/config.yml.

The Error:
cat /var/log/rexray/rexray.log : 

 time="2016-07-01T04:11:56Z" level=error msg="default module(s) failed to initialize" error.configKey=libstorage.server.services error.obj=<nil> time=1467346316
time="2016-07-01T04:11:56Z" level=error msg="error starting rex-ray" error.configKey=libstorage.server.services error.obj=<nil> time=1467346316
contents of the config file are:

The config: 
cat /etc/rexray/config.yml

rexray:
  storageDrivers:
- openstack
  openstack:
  authUrl: xxxx
  username: xxxx
  password: xxxx
  tenantName: xxxx
  regionName: xxxx

Replaced all original values with xxxx.

Provided the config file and also exported the Openstack environment variables, but still seeing these errors on service rexray status. Any assistance would be of great help. Thanks.

**Comment by cduchesne** [comment]
@rahuldivgan 

Can you post the contents of your /etc/rexray/config.yml in a codeblock? 

Also, can you run "rexray version" and "rexray volume -l debug"?

**Comment by clintonskitson** [comment]
Best thing to do here is to validate the actual settings with an export that can be provided from Horizon. It is likely that there is a mismatch of tenant or region.

**Comment by rahuldivgan** [comment]
The following are contents of /etc/rexray/config.yml

`# cat /etc/rexray/config.yml
rexray:
  storageDrivers:
  - openstack
openstack:
  authUrl: https://*****.com:5000/v2.0
  username: *****
  password: *****
  tenantName: *****
  regionName: *****
  availabilityZoneName: alln01-1-csi`

**Comment by rahuldivgan** [comment]
Unfortunately it is still the same format even after putting it in code block, hence attaching a screen shot, and have edited the and put stars * as I couldn't share the details. 
<img width="309" alt="screen shot 2016-07-01 at 11 20 31 am" src="https://cloud.githubusercontent.com/assets/16629093/16530668/199cb332-3f7e-11e6-8c3b-d375c0ad6240.png">

**Comment by rahuldivgan** [comment]
Hi @clintonskitson I have exported the exact same values as seen in Horizon. Kindly looking for additional help on this, thanks guys.

**Comment by clintonskitson** [comment]
Try a `rexray start -l debug -f` and send over the details if you can.

**Comment by rahuldivgan** [comment]
<img width="717" alt="screen shot 2016-07-01 at 2 35 08 pm" src="https://cloud.githubusercontent.com/assets/16629093/16535064/59ff5c3e-3f99-11e6-97e8-2597b97d6b35.png">

<img width="1377" alt="screen shot 2016-07-01 at 2 36 33 pm" src="https://cloud.githubusercontent.com/assets/16629093/16535073/63446f1e-3f99-11e6-82da-ffe7f5170fee.png">

**Comment by clintonskitson** [comment]
You are using RR 0.4.0 here which doesn't include Openstack driver yet.

Try `curl -sSL https://dl.bintray.com/emccode/rexray/install | sh -s -- stable 0.3.3` to get the last stable release that has the driver.
