### ISSUE TITLE
Failed to run rexray

### ISSUE THREAD

**Issue by pilgrim2go** [codedellemc/rexray#512]
Hi,

I got following error when running rexray (0.3.3)

```
docker run -tid --volume-driver=rexray -v vc-d-rdb:/mystore \
>   --name temp01 busybox
a7fdfaca97bf164566727431a585ae26f202725f095451797b0757caf30dfb34
docker: Error response from daemon: Container command 'sh' not found or does not exist..
```

the volume vc-d-rdb was created from snapshot ( by a volume created by rexray).

This issue even happens to newly created volume

```
docker volume create --driver rexray --opt size=10 --name hellopersistence
hellopersistence
```

and 

```
 docker run -tid --volume-driver=rexray -v hellopersistence:/mystore   --name temp02 busybox
a7c1897b4020d6798b327480f744e0547075b9d64225020a013645dca0341917
docker: Error response from daemon: Container command 'sh' not found or does not exist..
```

rexray version

```
rexray version
Binary: /usr/bin/rexray
SemVer: 0.3.3
OsArch: Linux-x86_64
Branch: v0.3.3
Commit: b30fb870b5b94cd8368824460ad020bfcf20be3a
Formed: Thu, 21 Apr 2016 19:41:36 UTC
```

and

```
cat /etc/*-release
NAME="Amazon Linux AMI"
VERSION="2016.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.03"
PRETTY_NAME="Amazon Linux AMI 2016.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2016.03
```

**Comment by kacole2** [comment]
Can you please give some more information? What storage driver and OS/AMI,  Docker version, and Steps to recreate?

Have you examined the logs or changed logging to debug and examined the logs?

Kendrick Coleman
kendrickcoleman.com
@KendrickColeman
github.com/kacole2

**Comment by kacole2** [comment]
@pilgrim2go sorry, please excuse my previous email. 

This could be related to #510 because we haven't called out support for Amazon Linux in our docs. Please try with Ubuntu or CentOS.

**Comment by derfloh** [comment]
@pilgrim2go have a look at #510 , I found a solution for Amazon Linux.. you just need to modify the initscript for docker.

**Comment by pilgrim2go** [comment]
Thank @derfloh : I'm to try it ( busy with other task).
