### ISSUE TITLE
Google Compute Engine (GCE) storage driver

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#523]
emccode/libstorage#394

- [x] executor
- [x] login/authentication from JSON key file
- [x] cluster session caching
- [x] volumes list
- [x] local device mapping
- [x] volume inspect
- [x] volume create
- [x] volume delete
- [x] volume attach
- [x] volume mount
- [x] volume unmount
- [x] volume detach
- [x] support standard or SSD persistent disks
- [x] tagging feature
- [x] pre-emption
- [x] tests
- [x] Add vagrantfile for testing

**Comment by codenrhoden** [comment]
I have all the major features working, just need to finish up my tests/test-plan, etc.  Need to make sure pre-emption is working as intended as well.

@cduchesne mentioned the desire for support of the rexray tag feature. This would be used to have `volumes ls` operations ignore volumes not created by rexray (ignoring boot volumes for instances, for example). Unfortunately, both tags and labels are part of the Beta API for GCE.

It does seem that the Beta API is a superset of v1. If we wanted to explore using this, we could swith which API we were using based on whether a tag/label was set. Meaning that if you configure the driver to use a label/ltag, it would use the beta API instead.

Regardless, I'd rather leave such a feature for a future enhancement.

Progress at https://github.com/codenrhoden/libstorage/tree/feature/gce if that wasn't obvious. :)

**Comment by codenrhoden** [comment]
a preliminary PR has been opened here: https://github.com/codedellemc/libstorage/pull/394

Just a couple things left to do.

**Comment by codenrhoden** [comment]
The only things missing here is a Vagrant based testplan (which will do multi-node testing, e.g. pre-emption), and the supporting docs. Working on Vagrant now!

**Comment by akutz** [comment]
Closed in favor of tracking this with [libStorage PR \#394](https://github.com/codedellemc/libstorage/pull/394) and listing milestones on the [REX-Ray project page](https://github.com/orgs/codedellemc/projects/1).

**Comment by cduchesne** [comment]
codedellemc/libstorage#394 merged... looks good to me. thanks @codenrhoden
