### ISSUE TITLE
Azure storage driver

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#528]
codedellemc/libstorage#421

**Comment by akutz** [comment]
Closed in favor of tracking this with [libStorage PR \#372](https://github.com/codedellemc/libstorage/pull/372) and listing milestones on the [REX-Ray project page](https://github.com/orgs/codedellemc/projects/1).

**Comment by cduchesne** [comment]
@codenrhoden - What is status of current work for this driver? What isn't functioning correctly as of yet and how much level of effort to get it functional enough for initial inclusion?

**Comment by akutz** [comment]
I know that Travis is working on it, but it's slated for 0.9.0 anyway, so I wasn't too concerned.

-- 
-a

**Comment by codenrhoden** [comment]
@cduchesne The first hold-up that I hit was that the executor was not distro independent. It was looking for a specific entry in a specific file, which happens to be differently handled between Debian based distros and RHEL based distros. I happened to start with CentOS, and CentOS completely failed. I suspect it works on Ubuntu. I have a fix for this, but have not yet opened a new PR with the changes.

Without a working executor, I have been unable to flush out long-tail issues that I have not hit yet. Code review looks pretty good -- I think things are structured in a good way and that modifications will be minor.  As it is today, the driver has a high probability of failing depending on your choice of distro.

**Comment by cduchesne** [comment]
Thanks for the hard work @codenrhoden . codedellemc/libstorage#421 has been merged
