### ISSUE TITLE
how to get device name

### ISSUE THREAD

**Issue by James-Dao** [codedellemc/rexray#543]
Hi, 
I am from DaoCloud. I found that i can get device name with 0.3.3. such as ,
- name: hello
  volumeid: 94c2340500000000
  availabilityzone: default
  status: ""
  volumetype: default
  iops: 0
  size: "8"
  networkname: ""
  attachments:
  - volumeid: 94c2340500000000
    instanceid: 7a30fff800000001
    devicename: /dev/scinia
    status: ""

now, i use 0.4.2 . i found the result is different. it does not show device name.

attachments:
- instanceID:
  id: 7213c89800000001
  driver: scaleio
  volumeID: 32bd63b600000002
  availabilityZone: default
  name: hello1
  size: 8
  id: 32bd63b600000002
  type: defaultSP

**Comment by rafajeng** [comment]
Hi, James

In Linux, the /dev/sd# may change, but the /dev/disk/by-id never changes. 

You can find Linux device name by:

	# rexray -s scaleio volume get
	- attachments:
	  - instanceID:
		  id: e7d7430600000001
		  driver: scaleio
		volumeID: **65d0392900000001**
	  availabilityZone: domain1
	  name: volrr1
	  size: 32
	  id: 65d0392900000001
	  type: pool_hdd

	# ls -l /dev/disk/by-id | grep scini
	lrwxrwxrwx 1 root root 12 Aug 30 15:07 emc-vol-_78b174b134243013_-**65d0392900000001** -> ../../**scinia**

	# scli --query_all_volumes
		Query-all-volumes returned 2 volumes
		Protection Domain 3df0992700000000 Name: domain1
		Storage Pool a7ca7bed00000000 Name: pool_hdd
		 Volume ID: **65d0392900000001** Name: volrr1 Size: 32.0 GB (32768 MB) Mapped to 1 SDC Thin-provisioned
	
	# [root@eric ~]# scli --query_all
	System Info:
        Product:  EMC ScaleIO Version: R2_0.6035.0
        ID:      _78b174b134243013_
        Manager ID:      0000000000000000
        Name:     sio11-linux

**Comment by cduchesne** [comment]
There may be a bug with how device name is reported - I will be looking into this.

**Comment by codenrhoden** [comment]
I know this is old, but for posterity before closing, the right way these days would be:

`rexray volume ls --path --format jsonp`
