### ISSUE TITLE
Rexray, ScaleIO, and shared file system

### ISSUE THREAD

**Issue by rafajeng** [codedellemc/rexray#547]
ScaleIO is a block SAN storage. So to allow two hosts to simultaneous access the same file system on a ScaleIO LUN, there has to be a clustered file system like VMFS, GFS2 and OCFS2. Another option is to put ScaleIO as a backend for NFS. 

Is there any similar feature for this function on Rexray roadmap?

Thanks

**Comment by codenrhoden** [comment]
There are no plans to introduce the auto-formatting of a clustered filesystem. There are talks around shared read-only mounts, and support for an NFS driver.

@cduchesne might care to say more, but I'm closing this for now
