### ISSUE TITLE
question: rexray with mesos & docker containerizer

### ISSUE THREAD

**Issue by mohamedhaleem** [codedellemc/rexray#557]
Greetings

I am trying out rexray with mesos/marathon

Could someone here help me with rexray in mesos with the docker containerizer

i looked at the example … here … 
http://rexray.readthedocs.io/en/stable/user-guide/schedulers/#mesos

and just have one clarification ...

 ```{
    "id": "nginx",
    "container": {
        "docker": {
            "image": "million12/nginx",
            "network": "BRIDGE",
            "portMappings": [{
                "containerPort": 80,
                "hostPort": 0,
                "protocol": "tcp"
            }],
            "parameters": [{
                "key": "volume-driver",
                "value": "rexray"
            }, {
                "key": "volume",
                "value": "nginx-data:/data/www"
            }]
        }
    },
    "cpus": 0.2,
    "mem": 32.0,
    "instances": 1
}

```
In the parameters section -
what does nginx-data refer to?

rexray commands are working from the host and i am able to list the volumes from our openstack/ceph storage and i can even mount the volumes like so.

cat /proc/mounts |grep rexray
/dev/vdd /var/lib/rexray/volumes/testing1234 ext4 rw,relatime,data=ordered 0 0

and unmount works too, all i need now is to get it working via docker/mesos/marathon

TIA
```

**Comment by cduchesne** [comment]
nginx-data would be the volume name... similar to your existing rexray volume testing1234
