### ISSUE TITLE
is scaleio-rest-gateway  SPOF?

### ISSUE THREAD

**Issue by slawekgh** [codedellemc/rexray#559]
I'm planning to design HA rexray architecture , I have (from top to bottom) several layers in my stack:
1. multiple swarm nodes 
2. multiple docker instances 
3. multiple scale-io SDC nodes with with multiple rexray services 
4. ONLY ONE SCALE-IO REST-GATEWAY
5. multiple (3) scale-io MDM nodes 
6. multiple scale-io SDS nodes 
7. multiple hardware boxes 

Is there any way to configure rexray with for example 3 scaleio-rest-gateways? If not it seems that we have spof in rexray-rest layer , if it fails I have a problem .... 

sl

**Comment by rafakei** [comment]
@slawekgh

There is HA for ScaleIO Gateway. Please check https://support.emc.com/docu67410_ScaleIO_2.x_Gateway_High_Availability_Technical_Notes.pdf?language=en_US
