### ISSUE TITLE
Seems that rexray is moving volumes only with gracefull docker daemon shutdown, not with entire server sudenly fail

### ISSUE THREAD

**Issue by slawekgh** [codedellemc/rexray#560]
Seems that rexray is moving volumes only if docker daemon was gracefully shutdown

I have 3 nodes swarm cluster:

```
[root@cent03 ~]# docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
3y19mapxua8lc0s5us1fvg5n7    cent04    Ready   Active
5c9oizwem0o0yprssb4w8v1an    cent05    Ready   Active
dawp36yd6dimy0d84ffkmr1lx *  cent03    Ready   Active        Leader
```

I have one service 

```
[root@cent03 ~]# docker service create --replicas 1 --name service_1 --mount type=volume,source=service_1_vol,target=/data,volume-driver=rexray ubuntu:14.04 tail -f /dev/null

[root@cent03 ~]# docker service ps service_1
ID                         NAME             IMAGE         NODE    DESIRED STATE  CURRENT STATE            ERROR
3czxnola1piof96bc9qsvmyp1  service_1.1      ubuntu:14.04  cent04  Running        Running 21 seconds ago
```

this service has one container - it works on node "cent04" where is also rexray /dev/scinia device:

```
[root@cent04 ~]# ls -l /dev/scini*
crw-r--r--. 1 root root 248, 0 Sep 16 10:31 /dev/scini
brw-rw----. 1 root disk 252, 0 Sep 16 11:27 /dev/scinia
```

next I simulate server down via killing all docker processes:

```
[root@cent04 ~]# ps -ef | grep docker
root      9506     1  0 11:21 ?        00:00:01 /usr/bin/dockerd
root      9509  9506  0 11:21 ?        00:00:00 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --shim docker-containerd-shim --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --runtime docker-runc
root      9960  9509  0 11:27 ?        00:00:00 docker-containerd-shim d47b88f44b97e434ce12e25ce0d48663122f7f9bf8dd3b63e5dd4fe77681fa2e /var/run/docker/libcontainerd/d47b88f44b97e434ce12e25ce0d48663122f7f9bf8dd3b63e5dd4fe77681fa2e docker-runc
[root@cent04 ~]# kill -9 9506 9509 9960
```

but (even after a while) /dev/scinia device still exists on failed node - seems like rexray didnt move this device to helathy node 

```
[root@cent04 ~]# ls -l /dev/scini*
crw-r--r--. 1 root root 248, 0 Sep 16 10:31 /dev/scini
brw-rw----. 1 root disk 252, 0 Sep 16 11:27 /dev/scinia
```

after a 10 minutes - the same:

```
[root@cent04 ~]# ls -l /dev/scini*
crw-r--r--. 1 root root 248, 0 Sep 16 10:31 /dev/scini
brw-rw----. 1 root disk 252, 0 Sep 16 11:27 /dev/scinia
```

and of course service tries to start on 2nd node but there is no volume :

```
[root@cent03 ~]# docker service  ps service_1
ID                         NAME             IMAGE         NODE    DESIRED STATE  CURRENT STATE                    ERROR
0o865nwkrk58dnjfq64nauy7f  service_1.1      ubuntu:14.04  cent05  Running        Starting less than a second ago
d796l8kyvt2c1l89jobhdo17q   \_ service_1.1  ubuntu:14.04  cent05  Shutdown       Failed 5 seconds ago             "starting container failed: Vo…"
ci8ukplmfaa6aan6ll7ppanb3   \_ service_1.1  ubuntu:14.04  cent05  Shutdown       Failed 11 seconds ago            "starting container failed: Vo…"
364olssbg6mf3eo53vuj54d6d   \_ service_1.1  ubuntu:14.04  cent05  Shutdown       Failed 16 seconds ago            "starting container failed: Vo…"
dgcwlhn394a7eadko4rrk1ybe   \_ service_1.1  ubuntu:14.04  cent05  Shutdown       Failed 22 seconds ago            "starting container failed: Vo…"
```

When I shutdown docker daemon gracefully rexray works fine and move volume from "dead node" to healthy node

```
[root@cent03 ~]# docker node ls
ID                           HOSTNAME  STATUS  AVAILABILITY  MANAGER STATUS
3y19mapxua8lc0s5us1fvg5n7    cent04    Ready   Active
5c9oizwem0o0yprssb4w8v1an    cent05    Ready   Active
dawp36yd6dimy0d84ffkmr1lx *  cent03    Ready   Active        Leader


[root@cent03 ~]# docker service create --replicas 1 --name service_3 --mount type=volume,source=service_3_vol,target=/data,volume-driver=rexray ubuntu:14.04 tail -f /dev/null
3ynluq8bekiy9z6lvvu3qucot

[root@cent03 ~]# docker service ls
ID            NAME       REPLICAS  IMAGE         COMMAND
3ynluq8bekiy  service_3  1/1       ubuntu:14.04  tail -f /dev/null


[root@cent03 ~]# docker service  ps service_3
ID                         NAME         IMAGE         NODE    DESIRED STATE  CURRENT STATE           ERROR
85hp1cy4xgra75dvqduiagc0b  service_3.1  ubuntu:14.04  cent05  Running        Starting 3 seconds ago
```

I login to cent05 and simulate server down - but this time via service docker stop  :

```
[root@cent05 ~]# ls -l /dev/scini*
crw-r--r--. 1 root root 248, 0 Sep 16 10:31 /dev/scini
brw-rw----. 1 root disk 252, 0 Sep 16 11:35 /dev/scinia
[root@cent05 ~]# service  docker  stop
Redirecting to /bin/systemctl stop  docker.service
```

/dev/scini disapeared:

```
[root@cent05 ~]# ls -l /dev/scini*
crw-r--r--. 1 root root 248, 0 Sep 16 10:31 /dev/scini
[root@cent05 ~]#
```

swarm migrated service to next node :

```
[root@cent03 ~]# docker service  ps service_3
ID                         NAME             IMAGE         NODE    DESIRED STATE  CURRENT STATE               ERROR
6e7pd9oncwar5lx903rpv1qgk  service_3.1      ubuntu:14.04  cent04  Running        Running about a minute ago
85hp1cy4xgra75dvqduiagc0b   \_ service_3.1  ubuntu:14.04  cent05  Shutdown       Running 5 minutes ago
[root@cent03 ~]#
```

and on healthy node there is migrated new scini device (/dev/scinib) :

```
[root@cent04 ~]# ls -l /dev/scini*
crw-r--r--. 1 root root 248,  0 Sep 16 10:31 /dev/scini
brw-rw----. 1 root disk 252,  0 Sep 16 11:27 /dev/scinia
brw-rw----. 1 root disk 252, 16 Sep 16 11:39 /dev/scinib
```

Seems that rexray moves volumes only with gracefull docker daemon shutdown ? What if server fails suddenly without grace docker shutdown ?

**Comment by kacole2** [comment]
@slawekgh this is a problem I ran into during testing ONLY using ScaleIO in a three node cluster. @cduchesne can explain it better but shutting off 1/3 of a ScaleIO cluster is removing a bunch of services, meta-data, etc. that would likely never happen in practice

Perhaps @cduchesne can go into more detail about the killing of docker processes, I just knew about graceful stop of docker service and shutting down a 1/3 of a ScaleIO cluster

**Comment by slawekgh** [comment]
what is a little bit strange - I made killall docker processes with virtualbox+rexray and it worked perfectly , with scaleio+rexray it doesnt. 

maybe we should ask important question - what triggers scaleio volume move operation from "failing" node to healthy one ? Is it server down ? or rexray service down ? or docker down (but only gracefully?) or scaleio service down ?

**Comment by rafakei** [comment]
Hi, @kacole2. I encountered the same problem. My setup is RHEL 7.2, Docker 1.12.1, Rexray 0.5.1, and ScaleIO 2.0.0.3. The ScaleIO is a 2-layer setup. So it does not share any node with swarm worker nodes that run the container. All hosts are physical bare-metals. 

	HostName	SIO_role			Swarm_Role
	eric		mdm1, sds1	 		manager(work0, but drained)
	fiona		mdm2, sds2		
	joanna		sdc					swarm work1
	leo			sdc					swarm work2
	shaoye		tb1, sds3, gw

My container initially runs on leo. Rexray automatically mapped the volume to leo. If I shut down leo by "poweroff", Rexray can correctly unmap volume from leo and map it to jaonna as Swarm fails over my container to joanna. 

However, if I shutdown leo by "poweroff -f" or simply just unplug the power cord, Rexray fails to unmap volume from leo even after Swarm has started my container on joanna. 

It seems the problem is only with "unmap" but not "re-map", because **after I unmapped the volume from leo manually by ScaleIO gui/cli, rexray automatically re-mapped it to joanna**. 

Please help look into Rexray "unmap" sequence in this scenario. 

My lab is accessible from EMC intranet. If you need, I can share the access. 

Thanks

**Comment by kacole2** [comment]
@cduchesne @akutz email sent about this Issue. Please take a look when you have time.

**Comment by cduchesne** [comment]
@slawekgh -  can you please post your configuration file? I don't see any log data for REX-Ray, so I can only make some assumptions.

My first guess would be you don't have preemption enabled. This is a feature that force unmaps a volume from a failed node, otherwise it will assume the volume is locked and active. It needs to be in all of your REX-Ray configuration files for it to function correctly.

```
libstorage:
  integration:
    volume:
      operations:
        mount:
          preempt: true
```

**Comment by slawekgh** [comment]
Seems that after preemption flag works great , thank You very much
