### ISSUE TITLE
Migrating volumes in AWS stopped working - "volume name already exists" message returned

### ISSUE THREAD

**Issue by boriska70** [codedellemc/rexray#561]
We use rexray to migrate volumes in AWS between different availability zones in the same region. 
Scenario:
- 2 volumes created in advance using AWS CLI, both in the same availability zone (e.g., ap-southeast-1a) with names serviceA-1-vol and serviceA-2-vol, for example
- Later 2 instances of service A start. The 1 instance starts in ap-southeast-1**a**, attaches the volume using rexray and works. The 2nd one starts in ap-southeast-1**b**, rexray discovers that volume is in different AZ, migrates it to its current zone (ap-southeast-1b ), attaches the volume and works. Volume discovery and selection is done by the volume name defined in the service parameters. Rexray runs as a part of the service A startup using CLI.

Till recently we used v.0.2.0 of rexray and the migration worked smoothly using the command:
`rexray volume create --volumeid=$volume_id --volumename=$1 --volumetype=$volume_type`

Now we moved to v.0.3.3 and the same command fails with message:
`FATA[0000] volume name already exists driverName=ec2 moduleName= volumeName=serviceA-2-vol`

Is that a bug? Is there any other way for doing the same thing? Any workaround?

Thanks!

**Comment by akutz** [comment]
Hi @boriska70,

This isn't an answer, but we are building RR 0.6.0-rc1 right now with EBS (new name for the old EC2 driver) support. Hopefully it will fix the issue. We now only scan for volumes in the same AZ to which the client belongs when considering collisions. @cduchesne, any thoughts?

**Comment by cduchesne** [comment]
@boriska70 

The movement of an EBS volume to another Region or AZ requires creating a snapshot of said volume, then copying that snapshot to destination Region/AZ, followed by creating a new volume from the new snapshot in the destination Region/AZ. Are you looking for REX-Ray to do this automatically, or to give you the ability to manage the process using multiple REX-Ray commands?

**Comment by akutz** [comment]
Hi @boriska70,

I may be wrong about the new EBS driver supporting this out of the gate. I think @cduchesne is going to chime into explain exactly why I'm so prone to insert my foot into my mouth sometimes :)
