### ISSUE TITLE
Does Rexray work with VNX2 5400?

### ISSUE THREAD

**Issue by UnclaimedPants** [codedellemc/rexray#569]
I have a vnx2 5400. Would rex-ray work with this? Or are the vnx2's not yet supported?

**Comment by kacole2** [comment]
@UnclaimedPants there is no VNX2 support today. There is also no open issue on on [libStorage](https://github.com/emccode/libstorage/issues) to add it as a feature. However, I know that Unity now has an accessible API and it *can* be done. We are open to community additions to libStorage to support Unity, but it's not on the current Roadmap
