### ISSUE TITLE
Explore requirements for deploying/running REX-Ray in a container

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#580]
Containerizing REX-Ray works in some limited quantities today, however we need to explore the requirements to make sure it works the way it is supposed to, for any driver that libStorage supports. We must also consider how different schedulers / systems could automatically provision REX-Ray as a containerized service.

**Comment by akutz** [comment]
Related to #684

**Comment by cduchesne** [comment]
closing due to #684
