### ISSUE TITLE
Enable client-side SSL certificates to enforce client authentication 

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#584]
With client-side certificates, we can more easily protect a REX-Ray server from accepting requests form an unauthorized REX-Ray client. We could further enhance this to allow specific resources / actions.

**Comment by akutz** [comment]
This exists but isn't enabled by default because shipping with default HTTPS using certificates included with the product is no more secure than plain-text.

**Comment by akutz** [comment]
Documentation for libStorage [client and server TLS](http://libstorage.readthedocs.io/en/stable/user-guide/config/#tcptls).

**Comment by cduchesne** [comment]
Great - this can track the inclusion into REX-Ray as part of deployment. We shouldn't have to ship with certs, as we could potentially generate them during implementation as an option.

https://golang.org/src/crypto/tls/generate_cert.go

**Comment by koensayr** [comment]
So what work is left to be done here @cduchesne ?

**Comment by codenrhoden** [comment]
Some additional goals:

- REX-Ray should manage known service hosts to facilitate usage
- Known hosts are used to automatically to trust connected service

Acceptance Criteria
- User is able to configure secure client connection from ENV variables, CLI, and YAML
- The RR client is able to connect using certs with or without cert verification
- RR client connection can use trusted hosts for connection

Definition of Done
- REX-Ray controller/client configuration of SSL is simple and consistent with other platforms
- Configuration of all aspects of SSL is documented
- SSL configuration is tested with default SSL certificates

**Comment by akutz** [comment]
HI @codenrhoden,

I would submit that this issue should be closed as it's already part of the product and has been since v0.1.0. The default-to-TLS is separate from client-side SSL and is tracked separately as well.

**Comment by codenrhoden** [comment]
@akutz I concur. Between the docs that went in with https://github.com/codedellemc/rexray/pull/796, and the simpler client config with https://github.com/codedellemc/libstorage/pull/447, the only work left is #583.
