### ISSUE TITLE
REX-Ray service dependent service support

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#587]
When using systemd and ScaleIO, a user must manually update the rexray service to start after the ScaleIO scini service, otherwise REX-Ray will fail to start every time the system boots. There is a chance this can affect other drivers that we support now as well as ones we plan to support in the future.

**Comment by cduchesne** [comment]
@akutz @codenrhoden - do we want to add support for starting REX-Ray after other dependent services start or do we want to just make the REX-Ray service auto restart?

For instance, with ScaleIO, we could do either of the following:

start rexray service after scini service:
```
[Unit]
Description=rexray
Before=docker.service
After=scini.service

[Service]
EnvironmentFile=/etc/rexray/rexray.env
ExecStart=/usr/bin/rexray start -f
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process

[Install]
WantedBy=docker.service
```

Or we could make rexray service auto restart:
```
[Unit]
Description=rexray
Before=docker.service

[Service]
EnvironmentFile=/etc/rexray/rexray.env
ExecStart=/usr/bin/rexray start -f
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process

Restart=on-failure
RestartSec=5

[Install]
WantedBy=docker.service
```

Any opinions?

**Comment by akutz** [comment]
Auto restart is a terrible idea and we should not even begin to consider supporting it IMO. We should suss out possible dependencies. That's the only sane path forward.

**Comment by cduchesne** [comment]
@akutz I agree that auto-restart isn't the best solution for this specific issue, however I believe there are use-cases as to why we should support it outside of this scope.

**Comment by cduchesne** [comment]
As of right now, I can only think of ScaleIO having a service dependency.

@codenrhoden does Ceph present any service depency?

**Comment by akutz** [comment]
Sure. My response was specific to the question at hand, not in general. Thank you for clarifying :)

**Comment by codenrhoden** [comment]
>@codenrhoden does Ceph present any service dependency?

No. Since the `rbd` kernel module doesn't have a background process/service attached to it, there is nothing depend on. the module needs to be installed (e.g. `modprobe`), but that's expected to be taken care of more along the lines of `/etc/modules` or equivalent.

**Comment by cduchesne** [comment]
Will we be updating script to take account of ScaleIO dependency?

**Comment by akutz** [comment]
Hi @cduchesne,

I would like to move this back to 0.8.0 as there's no reason it should take longer than a few minutes to do via the unit file's dependency section. Is there a reason you moved it in the first place?

**Comment by cduchesne** [comment]
You're more that welcome to move it back and push the quick fix - I had moved it aside only due to transition to a containerized option in which the systemd service becomes less relevant.

**Comment by akutz** [comment]
Except this pretends that the containerized option, which when you speak of it in this context and relevant to the other feature designated for 0.8.0 is Docker specific, is the primary or even recommend approach. It's not either IMO. Not while Dockers plugin model is so deficient. 

-- 
-a

**Comment by kacole2** [comment]
my $0.02... working with 3 ScaleIO Node cluster i had to use 

```
Restart=always
RestartSec=5
```

if the cluster is starting up and MDM2 loads first before finding MDM1 and `scini.service` starts then it fails. The first `on-failure` is clean so it doesn't try and restart it.
