### ISSUE TITLE
DEBU[0001] signalling executor lock - Oops, an error occured!

### ISSUE THREAD

**Issue by TwinForce** [codedellemc/rexray#593]
Hey guys,

i am a trainee in the secound year. Since 2 weeks i work with docker. 
After lots of problems with the configuration i stay in front of the next one with rexray.

My Situtation:
4 Linux Ubuntu (16.04) Docker node(vers. 1.12.1)
   3 node in Swarm
   1 node as Consul 
3 Windows 2012 R2 with ScaleIO (vers. 2.0.0.2)

When i mount a Volume direkt with ipadress in the Container it is possible to access the volume.

Now i want to use rexray to create a docker Volume but when i start the service i get an kind of error message.

End of the Debug Log:

> DEBU[0001] waiting on executor lock                      server=spot-cockatoo-ga service=scaleio  
>                                                                                  storageDriver=libstorage time=1476193150032 
>                                                                                  txCR=1476193150 txID=a6709b24-7335-4e94-7c6e-
>                                                                                  cf9bacf4a1f2
> DEBU[0001] signalling executor lock                       server=spot-cockatoo-ga service=scaleio 
>                                                                                  storageDriver=libstorage time=1476193150047 
>                                                                                  txCR=1476193150 txID=a6709b24-7335-4e94-7c6e-
>                                                                                  cf9bacf4a1f2
> Oops, an error occured!

  exit status 1

---

RexRay debug output.txt
(https://github.com/emccode/rexray/files/521944/RexRay.debug.output.txt)

RexRay execution Output.txt 
(https://github.com/emccode/rexray/files/521938/RexRay.execution.output.txt)

RexRay config.txt
(https://github.com/emccode/rexray/files/521946/RexRay.config.txt)

Docker information output.txt
(https://github.com/emccode/rexray/files/521952/Docker.information.output.txt)

---

I read a lot of google article and issues here and try the solution but nothing worked for me.
So please help me... I am despairing :-(

**Comment by kacole2** [comment]
Is there a reason you are using the old Swarm instead of using SwarmKit? 

Please look at [this guide and demo](https://github.com/codedellemc/demo/tree/master/demo-persistence-with-minecraft-docker) for possibly getting your straighted out. Note, you do not have to use Minecraft but shows you how to properly setup and use SwarmKit and REX-Ray. This works using the [ScaleIO Vagrant env](https://github.com/codedellemc/demo/tree/master/setup-scaleio-vagrant).

**Comment by TwinForce** [comment]
Thanks a lot for your fast answer! :-)
No there is no reason. I worked with an guide from my instructor.. it seems to be an older guide O.o
I will try it with your guide an hope it works :-)
