### ISSUE TITLE
Does Rexray 0.5.1 support with docker 1.12.1

### ISSUE THREAD

**Issue by pratapnanda** [codedellemc/rexray#595]
I have upgraded my docker to 1.12.1 and upgrade rexray 0.5.1.Now I am tying to check AWS EFS.
But when i start rexray ,it automatically failed.I don't understand the exact where is the issue .

`ubuntu@ucp-controller:/etc/rexray$ sudo rexray service start
Starting REX-Ray...FAILED!
` 
error log
`time="2016-10-12T10:24:57Z" level=error msg="default module(s) failed to initialize" error.driver=ec2 time=1476267897033
time="2016-10-12T10:24:57Z" level=error msg="error starting rex-ray" error.driver=ec2 time=1476267897033
`
**`ubuntu@ucp-controller:/etc/rexray$ **docker version****
Client:
 Version:      1.12.1-cs1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   e7f4338
 Built:        Wed Sep 21 21:05:28 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1-cs1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   e7f4338
 Built:        Wed Sep 21 21:05:28 2016
 OS/Arch:      linux/amd64
`
**`ubuntu@ucp-controller:/etc/rexray$ **rexray version****
## REX-Ray

Binary: /usr/bin/rexray
SemVer: 0.5.1
OsArch: Linux-x86_64
Branch: v0.5.1
Commit: e2c3165ce26cdbd8be76c3f6bde31db8618ae306
Formed: Wed, 14 Sep 2016 19:59:58 UTC
## libStorage

SemVer: 0.2.1
OsArch: Linux-x86_64
Branch: v0.5.1
Commit: 2f7210c90252a4e1c9fb011ba29158cb0facb516
Formed: Wed, 14 Sep 2016 19:58:39 UTC
`
**ubuntu@ucp-controller:/etc/rexray$ cat config.yml**
rexray:
  logLevel: warn
  storageDrivers:
- ec2
  volume:
    mount:
      preempt: true
  aws:
  accessKey: xxxxx
  secretKey: xxxxx

**Comment by codenrhoden** [comment]
Hi @pratapnanda 

One thing I immediately notice is that you mention that you are trying to use "AWS EFS", but your output shows that you've tried to configure a driver named `ec2`.

rexray v0.3.3 and earlier did have an `ec2` driver, and that was actually for EBS volumes. Starting with rexray v0.4.0 ec2 was temporarily removed, and is making a comeback in in v0.6.0 (coming out soon, in Release Candidate form right now) as the `ebs` drivers.  You will need to configure a driver named `efs`, not `ec2`.

Docs on the EFS driver are here: http://libstorage.readthedocs.io/en/stable/user-guide/storage-providers/#aws-efs

You may also find the config file generator useful: http://rexrayconfig.codedellemc.com/

A working `/etc/rexray/config.yml` file for EFS would be more like the following:

```
rexray:
  logLevel: debug
libstorage:
  service: efs
  integration:
    volume:
      operations:
        mount:
          preempt: true
efs:
  accessKey: xxxx
  secretKey: xxxx
```

**Comment by kacole2** [comment]
@pratapnanda v0.6.3 is now available. is this solved? can we close the issue?

**Comment by pratapnanda** [comment]
@kacole2 -Yes ,Please close this issue .Thank you !!!
