### ISSUE TITLE
How to exclude a volume that is configured in de VOLUME parameter in Docker file

### ISSUE THREAD

**Issue by Krieke** [codedellemc/rexray#597]
Currently I depend on a docker image that I directly use from docker hub. In the Docker file there is a VOLUME parameter that lists 2 volumes. But in our scenario we would like to mount only one particular volume via rex-ray to an external volume (in this case an EC2 volume on AWS).

When trying to launch the docker image I always get issue when I only map one volume that is listed in the Docker file VOLUME parameter. When I map both of them there isn't an issue.

So my question: does rex-ray require all the volumes that are listed in the Docker file VOLUME parameter to be mapped to an external volume path? Can this be overruled during launching of the docker image. 

The only other option that I have is to fork the git repo and remove the specific volume from the VOLUME parameter in the Docker file.

While reading the rex-ray documentation I couldn't find a clear answer on this.

Kind regards,

Daniel

**Comment by kacole2** [comment]
@Krieke this is not a problem with REX-Ray but how Docker handles the `docker run` command with a `--volume-driver` parameter. Today, if you are using the `docker run` command and the `--volume-driver` flagged is used, it will create an anonymous volume on the storage backend if a mapping is not listed as `-v myvol:/path/in/container`. There is no way to specify using only 1 of the `VOLUME`s in the Dockerfile.

However, this is solved if you are using the new Docker Swarm Mode with SwarmKit in 1.12.1. Docker has implemented the `docker service` feature which does volume drivers on a per-volume basis. 
```
docker service create --replicas 1 --name pg -e POSTGRES_PASSWORD=mysecretpassword --mount type=volume,target=/var/lib/postgresql/data,source=pg_data,volume-driver=rexray postgres
```

**Comment by kacole2** [comment]
@Krieke i may stand corrected. @clintonskitson pointed me to something that says the volume-driver only has impact if the name specified is not known by docker. So you should pre-create a volume with `local` driver and then specify that volume by name.
