### ISSUE TITLE
Unable to detach existing and attached volume

### ISSUE THREAD

**Issue by vladimirvivien** [codedellemc/rexray#610]
This may be a bug in the libstorage client code.

I was unable to detach an existing volume that was attached using the virtualbox driver.  In the end, I used direct `curl` command to detach the volume.  See this gist page for detail https://gist.github.com/vladimirvivien/3569c26754647eb977388f24a8bd7350.

**Comment by akutz** [comment]
I'm fairly certain this is related to #609 and its solution will be this issue's as well.

**Comment by vladimirvivien** [comment]
@akutz as an update, that volume (which I could not remove) was created with an earlier version of rexray.  So not sure if that is relevant. Though I was able to remove it with a direct curl call.

**Comment by akutz** [comment]
@vladimirvivien The issue you're seeing is #609, not the version of RR that create the volume. But thanks for the info. More diag is almost never a bad thing.

**Comment by akutz** [comment]
Closed with #635.
