### ISSUE TITLE
Using docker volume driver from rexray

### ISSUE THREAD

**Issue by TamasSzerb** [codedellemc/rexray#621]
Hello,

I'd use DC/OS rexray driver for persistent storage on zzure, but as I see rexray does not support the azure yet. I wonder, that if the docker can use azure with https://github.com/Azure/azurefile-dockervolumedriver it might happen that rexray can support docker volume driver, so the azure as well.

In this case, could you please help me how to use docker volume driver from rexray?

Thanks,

Tamas

**Comment by kacole2** [comment]
@TamasSzerb Azure is not a supported platform within REX-Ray. libStorage is the main workhorse here and there is an issue here https://github.com/codedellemc/libstorage/issues/198.  There has been some talk of Microsoft wanting to write the driver for libStorage but I can't comment on its status. 

Please close the issue if this answers your question.
