### ISSUE TITLE
Add Azure storage driver

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#711]
codedellemc/libstorage#372

v1
======
- [ ] Azure executor
- [ ] ls volumes
- [ ] local device mapping
- [ ] attachment filters
- [ ] volume status
- [ ] volume inspect
- [ ] volume create
- [ ] volume delete
- [ ] volume attach
- [ ] volume mount
- [ ] volume unmount
- [ ] volume detach
- [ ] docker volume create
- [ ] docker volume mount
- [ ] docker volume unmount
- [ ] docker volume delete
- [ ] docker volume mount preempt
- [ ] tests
- [ ] docs

**Comment by jzampieron** [comment]
Is this related to #361 ?

**Comment by cduchesne** [comment]
Yes, I should have linked to #361. If you check out the PR it's mostly ready to be merged.

**Comment by jzampieron** [comment]
I saw. Thanks. Waiting anxiously for that PR to merge in to try it out.

**Comment by cduchesne** [comment]
closed due to realizing this was already a previous issue #528 that had been closed
