### ISSUE TITLE
Add troubleshooting guide to docs

### ISSUE THREAD

**Issue by cantbewong** [codedellemc/rexray#715]
# Summary
Add troubleshooting guide to docs.

# New Feature
It would be useful to consolidate the troubleshooting information that is currently dispersed in places like the new issue template and the Slack channel history into a new troubleshooting section within the docs. It would also be useful to genrate some new material

**Comment by cantbewong** [comment]
created PR to add troubleshooting guide
https://github.com/codedellemc/rexray/pull/728

**Comment by cduchesne** [comment]
#739 merged
