### ISSUE TITLE
Missing Instance ID

### ISSUE THREAD

**Issue by oddmarthon-lende** [codedellemc/rexray#722]
# Summary
I've tried setting up rexray using Amazon EBS and Virtualbox.
With EBS driver i am able to list the volumes ive already created on Amazon, but i can't create.
With virtualbox i can also create volumes

level=error msg="missing instance ID" host="unix:///var/run/libstorage/353751457.sock"

What does "missing instance ID" mean ? I get this error with both VBox and EBS.

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.7.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a20a838ca70838a914b632637398824fcb10d0db
Formed: Mon, 23 Jan 2017 16:14:32 CET

libStorage
----------
SemVer: 0.4.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a1103d3f215117f7b9f51dae2b24f852c9c54995
Formed: Mon, 23 Jan 2017 16:14:12 CET
```

## Logs
● rexray.service - rexray
   Loaded: loaded (/etc/systemd/system/rexray.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-02-12 01:18:57 CET; 12s ago
 Main PID: 5140 (rexray)
    Tasks: 8 (limit: 4915)
   Memory: 34.3M
      CPU: 1.485s
   CGroup: /system.slice/rexray.service
           └─5140 /usr/bin/rexray start -f

Feb 12 01:18:58 aspire rexray[5140]: SemVer: 0.4.0
Feb 12 01:18:58 aspire rexray[5140]: OsArch: Linux-x86_64
Feb 12 01:18:58 aspire rexray[5140]: Branch: v0.7.0
Feb 12 01:18:58 aspire rexray[5140]: Commit: a1103d3f215117f7b9f51dae2b24f852c9c54995
Feb 12 01:18:58 aspire rexray[5140]: Formed: Mon, 23 Jan 2017 16:14:12 CET
Feb 12 01:19:01 aspire rexray[5140]: time="2017-02-12T01:19:01+01:00" level=warning msg="executor not supported" host="unix:///var/run/libstorage/353751457.sock" server=coconut-cub-bl service=ebs storageDriver=libstorage time=1486858741027
Feb 12 01:19:01 aspire rexray[5140]: time="2017-02-12T01:19:01+01:00" level=warning msg="cannot get local deviecs" error="executor not supported" host="unix:///var/run/libstorage/353751457.sock" integrationDriver=linux osDriver=linux server=coconut-cub-bl service=ebs storageDriver=libstorage time=1486858741124 txCR=1486858741 txID=f61a7f17-8fd6-43fd-6d0b-f7679b5b84f3
Feb 12 01:19:01 aspire rexray[5140]: time="2017-02-12T01:19:01+01:00" level=error msg="missing instance ID" host="unix:///var/run/libstorage/353751457.sock" route=volumesForService server=coconut-cub-bl service=ebs storageDriver=ebs task=0 time=1486858741176 tls=false txCR=1486858741 txID=f61a7f17-8fd6-43fd-6d0b-f7679b5b84f3
Feb 12 01:19:01 aspire rexray[5140]: time="2017-02-12T01:19:01+01:00" level=error msg="missing instance ID" host="unix:///var/run/libstorage/353751457.sock" route=volumesForService server=coconut-cub-bl service=ebs time=1486858741179 tls=false txCR=1486858741 txID=f61a7f17-8fd6-43fd-6d0b-f7679b5b84f3
Feb 12 01:19:01 aspire rexray[5140]: time="2017-02-12T01:19:01+01:00" level=error msg="error initializing the path cache" async=true error.inner.service=ebs error.status=500 host="unix:///var/run/libstorage/353751457.sock" integrationDriver=linux osDriver=linux service=ebs storageDriver=libstorage time=1486858741181

After i try to run a container with the EBS volume it crashes:

docker run -it --volume-driver=rexray -v vol-06b6379939108dfcf:/test busybox /bin/sh

$> rexray service status

● rexray.service - rexray
   Loaded: loaded (/etc/systemd/system/rexray.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2017-02-12 01:19:38 CET; 43s ago
  Process: 5140 ExecStart=/usr/bin/rexray start -f (code=exited, status=2)
 Main PID: 5140 (code=exited, status=2)

Feb 12 01:19:38 aspire rexray[5140]:         /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/router/volume/volume_routes.go:403 +0x343
Feb 12 01:19:38 aspire rexray[5140]: github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services.execTask(0xc4204463c0)
Feb 12 01:19:38 aspire rexray[5140]:         /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services/services_task.go:78 +0x732
Feb 12 01:19:38 aspire rexray[5140]: github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services.(*storageService).Init.func1(0xc42000e5c0)
Feb 12 01:19:38 aspire rexray[5140]:         /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services/services_storage.go:29 +0x73
Feb 12 01:19:38 aspire rexray[5140]: created by github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services.(*storageService).Init
Feb 12 01:19:38 aspire systemd[1]: rexray.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 12 01:19:38 aspire rexray[5140]:         /home/travis/gopath/src/github.com/codedellemc/rexray/vendor/github.com/codedellemc/libstorage/api/server/services/services_storage.go:31 +0xc8
Feb 12 01:19:38 aspire systemd[1]: rexray.service: Unit entered failed state.
Feb 12 01:19:38 aspire systemd[1]: rexray.service: Failed with result 'exit-code'.

**Comment by akutz** [comment]
Hi @oddmarthon-lende,

This line in the log is disconcerting:

```bash
Feb 12 01:19:01 aspire rexray[5140]: time="2017-02-12T01:19:01+01:00" level=warning msg="executor not supported" host="unix:///var/run/libstorage/353751457.sock" server=coconut-cub-bl service=ebs storageDriver=libstorage time=1486858741027
```

The executor determines if a client is supported by invoking some logic on the client. For EBS an attempt is made to query the EC2 private IP that returns information about an EC2 node. If the executor is indicating `ebs` is not supported then this code is returning `false`:

```go
const (
	raddr  = "169.254.169.254"
	mdtURL = "http://" + raddr + "/latest/meta-data/"
	iidURL = "http://" + raddr + "/latest/dynamic/instance-identity/document"
	bdmURL = "http://" + raddr + "/latest/meta-data/block-device-mapping/"
)

// IsEC2Instance returns a flag indicating whether the executing host is an EC2
// instance based on whether or not the metadata URL can be accessed.
func IsEC2Instance(ctx types.Context) (bool, error) {
	client := &http.Client{Timeout: time.Duration(1 * time.Second)}
	req, err := http.NewRequest(http.MethodHead, mdtURL, nil)
	if err != nil {
		return false, err
	}
	res, err := doRequestWithClient(ctx, client, req)
	if err != nil {
		if terr, ok := err.(net.Error); ok && terr.Timeout() {
			return false, nil
		}
		return false, err
	}
	if res.StatusCode >= 200 || res.StatusCode <= 299 {
		return true, nil
	}
	return false, nil
}
```

So a dumb question, but are you running this on an Amazon EC2 instance? Because the EFS and EBS drivers are only supported on EC2 instances. Likewise, the VirtualBox driver is only supported on a VBox VM.

**Comment by oddmarthon-lende** [comment]
Ah...
