### ISSUE TITLE
Permission denied error when writing to AWS EBS volume attached to Docker container

### ISSUE THREAD

**Issue by spriyadharshini** [codedellemc/rexray#731]
# Summary
I'm trying to create persistence storage for Docker containers running in AWS EC2 instance using RexRay. I am able to create and attach volume to the container. But when I try to write a file in the volume, I great 'permission denied' error.

I'm using CentOS 7 
RexRay version -
Binary: /usr/bin/rexray
SemVer: 0.3.3
OsArch: Linux-x86_64
Branch: v0.3.3
Commit: b30fb870b5b94cd8368824460ad020bfcf20be3a
Formed: Thu, 21 Apr 2016 19:41:36 UTC

## Expected Behavior
I should be able to create a new file in the attached volume

## Actual Behavior
Permission denied error

## Steps To Reproduce
docker volume create --driver=rexray --name=rexrayvolume --opt=size=1
docker run -ti --name=rex01 --volume-driver=rexray -v rexrayvolume:/rexrayvolume busybox
/ # echo 'test' > /rexrayvolume/file1
sh: can't create /rexrayvolume/file1: Permission denied
/ #
/ # ls -ltr
total 20
drwxr-xr-x    2 root     root         12288 Jan 12 18:10 bin
drwxrwxrwt    2 root     root             6 Jan 12 18:10 tmp
drwxr-xr-x    4 root     root            30 Jan 12 18:10 var
drwxr-xr-x    3 root     root            18 Jan 12 18:10 usr
drwxr-xr-x    2 nobody   nogroup          6 Jan 12 18:10 home
dr-xr-xr-x   13 root     root             0 Feb 15 18:32 sys
drwx------    2 root     root          4096 Feb 15 18:54 rexrayvolume
drwxr-xr-x    2 root     root           124 Feb 15 19:05 etc
drwxr-xr-x    3 root     root            21 Feb 15 19:06 run
dr-xr-xr-x  118 root     root             0 Feb 15 19:06 proc
drwxr-xr-x    5 root     root           380 Feb 15 19:06 dev
drwxr-xr-x    2 root     root            26 Feb 15 19:09 root

## Configuration Files
Please paste any related configuration files, such as `/etc/rexray/config.yml`
in this section. Please use the appropriate formatting when pasting YAML.
content. For example:

rexray:
  logLevel: debug
  storageDrivers:
  - ec2
  volume:
    mount:
      preempt: true
aws:
  accessKey: xyz
  secretKey: abc

**Comment by kacole2** [comment]
Any reason you are on v0.3.3? You should be using the latest release which is 0.7

**Comment by spriyadharshini** [comment]
Hi, I was trying this couple of months ago when 0.3.3 was the stable version. I’ll try 0.7 and let you know.

Thanks
Priya

**Comment by spriyadharshini** [comment]
I tried the latest 0.7. Rexray isnt active and running.

Here is the version
[root@ip-172-168-2-111 centos]# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.7.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a20a838ca70838a914b632637398824fcb10d0db
Formed: Mon, 23 Jan 2017 15:14:32 UTC

libStorage
----------
SemVer: 0.4.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a1103d3f215117f7b9f51dae2b24f852c9c54995
Formed: Mon, 23 Jan 2017 15:14:12 UTC
[root@ip-172-168-2-111 centos]#

Below is the output of status 
[root@ip-172-168-2-111 centos]# systemctl status rexray -l
â rexray.service - rexray
   Loaded: loaded (/etc/systemd/system/rexray.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2017-02-15 21:14:08 UTC; 8s ago
  Process: 2648 ExecStart=/usr/bin/rexray start -f (code=exited, status=0/SUCCESS)
 Main PID: 2648 (code=exited, status=0/SUCCESS)

Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: ----------
Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: SemVer: 0.4.0
Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: OsArch: Linux-x86_64
Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: Branch: v0.7.0
Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: Commit: a1103d3f215117f7b9f51dae2b24f852c9c54995
Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: Formed: Mon, 23 Jan 2017 15:14:12 UTC
Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: time="2017-02-15T21:14:08Z" level=error msg="error starting libStorage server" error.configKey=libstorage.server.services error.obj=<nil> time=1487193248488
Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: time="2017-02-15T21:14:08Z" level=error msg="default module(s) failed to initialize" error.configKey=libstorage.server.services error.obj=<nil> time=1487193248488
Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: time="2017-02-15T21:14:08Z" level=error msg="daemon failed to initialize" error.obj=<nil> error.configKey=libstorage.server.services time=1487193248488
Feb 15 21:14:08 ip-172-168-2-111.ec2.internal rexray[2648]: time="2017-02-15T21:14:08Z" level=error msg="error starting rex-ray" error.obj=<nil> error.configKey=libstorage.server.services time=1487193248488

**Comment by akutz** [comment]
Hi @spriyadharshini,

When you create a new issue, the template indicates how to supply logs and configuration information. It specifically requests and details the need and how to use appropriate formatting. Please update your problem description and subsequent comments using the appropriate formatting. It will make it possible for us to assist you.

**Comment by codenrhoden** [comment]
@spriyadharshini those errors lots of missing keys/entries in your config file. Did you update the config.yml file for the new format, or just use the previous one you had? the old one won't work.

it changed quite a bit after 0.3.3. But, @kacole2 did create a nifty tool that will make it a lot easier on you. Check out http://rexrayconfig.codedellemc.com/

**Comment by codenrhoden** [comment]
Just using your previous config file as an example, a new one would look more like:

```yaml
rexray:
  logLevel: debug
libstorage:
  service: ebs
  integration:
    volume:
      operations:
        mount:
          preempt: true
ebs:
  accessKey: xyz
  secretKey: abc
```

**Comment by spriyadharshini** [comment]
Thanks. My Rexray 0.7 is up with the updated config.yml.
But I'm encountering the same issue 'permission denied' when trying to access the mounted EBS volume. Its strange because I wasnt facing this problem when I was using v0.3.3 sometime around September 2016.

[root@ip-172-168-2-111 centos]# docker run -ti --name=rex01 --volume-driver=rexray -v testvolume6:/testvolume6 busybox
/ # df /testvolume6/
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/xvdf               999320      2568    927940   0% /testvolume6
/ # echo "test">/testvolume6/file
sh: can't create /testvolume6/file: Permission denied
/ #
/ # ls -lrt
total 20
drwxr-xr-x    2 root     root         12288 Jan 12 18:10 bin
drwxrwxrwt    2 root     root             6 Jan 12 18:10 tmp
drwxr-xr-x    4 root     root            30 Jan 12 18:10 var
drwxr-xr-x    3 root     root            18 Jan 12 18:10 usr
drwxr-xr-x    2 nobody   nogroup          6 Jan 12 18:10 home
dr-xr-xr-x   13 root     root             0 Feb 15 20:44 sys
drwx------    2 root     root          4096 Feb 15 21:28 testvolume5
drwxr-xr-x    2 root     root           124 Feb 15 21:48 etc
drwxr-xr-x    3 root     root            21 Feb 15 21:49 run
dr-xr-xr-x  136 root     root             0 Feb 15 21:49 proc
drwxr-xr-x    5 root     root           380 Feb 15 21:49 dev
drwxr-xr-x    2 root     root            26 Feb 15 21:49 root

**Comment by kacole2** [comment]
@spriyadharshini please make sure you are using proper markdown formatting. Please look at the [Troubleshooting section for EBS](http://libstorage.readthedocs.io/en/stable/user-guide/storage-providers/#aws-ebs) to verify all the correct permissions are enabled for either IAM or your keys

**Comment by spriyadharshini** [comment]
@kacole2 , I checked my IAM policies. Earlier I had given 'AmazonEC2FullAccess'. After looking into Troubleshooting section, I added 'AmazonElasticFileSystemFullAccess'. I also generated new access keys to see if it helps. But it didnt.
Like I mentioned earlier, I am still getting 'Permission denied' error when trying to read or write into the mounted EBS volume.

**Comment by kacole2** [comment]
@spriyadharshini i'm certain it's a permissions issue and not a REX-Ray issue. I just spun up a new CentOS image and tested without issue. Here are the steps I used:

Launch an AWS CentOS 7.1 Image. I used Codenvy_Centos7_1_AMI-launch-v3.13.4.4-1-HVM (ami-0889df62) in the N. Virginia Region

This has docker installed so I upgraded Docker:
```
$ sudo yum -y update && sudo yum -y upgrade && sudo yum upgrade docker -y
```

Installed REX-Ray:
```
curl -sSL https://dl.bintray.com/emccode/rexray/install | sh
```

Added my config file to `/etc/rexray/config.yml`:
```
libstorage:
  service: ebs
  integration:
    volume:
      operations:
        mount:
          preempt: true
ebs:
  accessKey: mykey
  secretKey: mysecretkey
```

Followed the same exact instructions you laid out with no issue.
```
[centos@ip-172-31-4-201 ~]$ docker run -ti --name=rex01 --volume-driver=rexray -v testvolume6:/testvolume6 busybox
/usr/bin/docker-current: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See '/usr/bin/docker-current run --help'.
[centos@ip-172-31-4-201 ~]$ sudo docker run -ti --name=rex01 --volume-driver=rexray -v testvolume6:/testvolume6 busybox
Unable to find image 'busybox:latest' locally
Trying to pull repository docker.io/library/busybox ...
sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e: Pulling from docker.io/library/busybox
4b0bc1c4050b: Pull complete
Digest: sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e
Status: Downloaded newer image for docker.io/busybox:latest
/ # df /testvolume6/
Filesystem           1K-blocks      Used Available Use% Mounted on
/dev/xvdf             16382844     45084  15482516   0% /testvolume6
/ # echo "test">/testvolume6/file
/ # cat /testvolume6/file
test
/ # ls -lrt
total 44
drwxr-xr-x    2 root     root         12288 Jan 12 18:10 bin
drwxrwxrwt    2 root     root          4096 Jan 12 18:10 tmp
drwxr-xr-x    4 root     root          4096 Jan 12 18:10 var
drwxr-xr-x    3 root     root          4096 Jan 12 18:10 usr
drwxr-xr-x    2 nobody   nogroup       4096 Jan 12 18:10 home
drwxr-xr-x    2 root     root          4096 Feb 16 14:52 etc
dr-xr-xr-x   13 root     root             0 Feb 16 14:52 sys
drwxr-xr-x    3 root     root          4096 Feb 16 14:52 run
dr-xr-xr-x  196 root     root             0 Feb 16 14:52 proc
drwxr-xr-x    5 root     root           380 Feb 16 14:52 dev
drwxr-xr-x    2 root     root          4096 Feb 16 14:53 root
drwx------    2 root     root          4096 Feb 16 14:53 testvolume6
```

**Comment by spriyadharshini** [comment]
@kacole2 Thanks for recreating the steps. I tried with the AMI that you have shared and followed the steps that I had used earlier and it worked this time. So it was not a permission issue. The issue might be with the AMI CentOS Linux 7 x86_64 HVM EBS 1602-b7ee8a69-ee97-4a49-9e68-afaee216db2e-ami-d7e1d2bd.3 (ami-6d1c2007).
Thanks much for supporting to resolve.
