### ISSUE TITLE
Documentation for REX-Ray Docker Plug-ins

### ISSUE THREAD

**Issue by cduchesne** [codedellemc/rexray#746]
Add documentation for each of the docker plug-ins

**Comment by vchrisb** [comment]
There is a small typo on https://hub.docker.com/r/rexray/scaleio/
docker **plug-in** install rexray/scaleio:0.7.20 should be **plugin**

**Comment by cduchesne** [comment]
Updated, thanks!

**Comment by cduchesne** [comment]
merged #756, #758, #760
