### ISSUE TITLE
Are there any performance and overhead issues using rexray for database storage?

### ISSUE THREAD

**Issue by kitgary** [codedellemc/rexray#764]
Hi,

First of all, thanks for building this great docker plugin, I got a few questions about using rexray in production.

 I am planning to deploy hdfs, mysql and cassandra cluster using Docker Swarm, and I want to use rexray to manage database storage with AWS EBS, I did read some articles about performance issue using database in container, does rexray introduce any significant overhead? What is the best method for deploying database container with rexray?

I don't have any experience to manage Docker database storage, I am sorry if my question doesn't make sense.

Ths

**Comment by kacole2** [comment]
Hi @kitgary. REX-Ray is a control plane tool. There is no introduction or shim into the database path. REX-Ray will not add any latency because it's not in the data plane. It's an orchestrator for control plane operations of a volume. Hope that helps.

**Comment by codenrhoden** [comment]
Hi @kitgary. Feel free to re-open if there is more we can answer here.
