### ISSUE TITLE
Update company logo on official docs

### ISSUE THREAD

**Issue by clintonskitson** [codedellemc/rexray#770]
The official docs still include a logo from EMC {code} in the top right. We should update this to include {code} by Dell EMC instead.

http://rexray.readthedocs.io/en/stable/

**Comment by akutz** [comment]
Hi Clint,

Please provide, or have someone provide, a graphic on white/solid/transparent background, and I will convert it into an SVG then web font.

**Comment by codenrhoden** [comment]
I captured this in https://github.com/codedellemc/libstorage/issues/262 as well.

**Comment by koensayr** [comment]
@cantbewong The SVG requested can be found on the team's Google Drive.

**Comment by clintonskitson** [comment]
Logo has been delivered to @akutz

**Comment by amandakatona** [comment]
What's the ETA of this fix pls?

**Comment by akutz** [comment]
Hi @amandakatona,

I returned to work today. I'll have it completed today or tomorrow. Thank you for following up on this. Please keep in mind, however, that it won't be reflected in the default site until the next GA release as that is when the `/stable` section of the documentation is updated.

**Comment by amandakatona** [comment]
Got it! This change will be reflected in the 0.8.2 release. Putting the SVG file into slack for you - GitHub doesn't support uploading SVG to this.

**Comment by akutz** [comment]
FWIW, turns out I didn't need the SVG anyway. I forgot I chopped the icon from the text originally.

![image](https://cloud.githubusercontent.com/assets/101085/24121847/bca23476-0d87-11e7-8ed5-a000e1296191.png)
