### ISSUE TITLE
Document managed plugin build process

### ISSUE THREAD

**Issue by clintkitson** [codedellemc/rexray#797]
Documentation for building REX-Ray works well. It looks like the documentation that describes how to build a Docker managed plugin are not there today.

It would be great to have a couple of things documented.
- Describing the build of an existing plugin
- The minimum requirements for making sure a new plugin can be built in a container

**Comment by akutz** [comment]
Hi @clintonskitson,

This is a great suggestion, especially the first point. I'm not sure we can accurately describe the minimum requirements in a broad sense though. It will vary per driver.
