### ISSUE TITLE
How to add command options for rexray/s3fs?

### ISSUE THREAD

**Issue by pascalim** [codedellemc/rexray#809]
I wanted to know how to add options to the s3fs command from the rexray/s3fs volume plugin? i.e. adding the `allow_other` option

**Comment by akutz** [comment]
Hi @pascalim,

You should be able to set the env var `S3FS_OPTIONS` to the options string you want to use.

**Comment by pascalim** [comment]
Hey @akutz, tried doing this with `docker plugin set rexray/s3fs S3FS_OPTIONS=allow_other` but docker complains about `Error response from daemon: setting "S3FS_OPTIONS" not found in the plugin configuration`

**Comment by akutz** [comment]
Hi @pascalim,

Doh! I guess we forgot to include it in the list of blessed env var names. I'll get a patch for that soon.

**Comment by codenrhoden** [comment]
This is available now as `rexray/s3fs:0.9.1-rc2`.

The `latest` tag will be updated once 0.9.1 is GA.
