### ISSUE TITLE
Is there any plan to support openstack ?

### ISSUE THREAD

**Issue by shamimgeek** [codedellemc/rexray#810]
Is there any plan to support for Openstack and Eucalyptus [ aws compatible cloud ] ?

**Comment by codenrhoden** [comment]
@shamimgeek

No plans for Eucalyptus, but OpenStack is queued up for the next release. See these existing issues and PR:
#530, codedellemc/libstorage#182, codedellemc/libstorage#243,

**Comment by shamimgeek** [comment]
Thanks for your reply.
all the best for your hard work towards making rexray most trusted tool for managing persistent volumes in cloud.
Regards
Shamim

**Comment by akailash** [comment]
Hi, Is this released already? From the release notes, it looks like these changes went in? Looking forward to using this on openstack in docker swarm for persistant storage.

**Comment by akutz** [comment]
Yep, it's available today.

**Comment by akailash** [comment]
Thanks. I have got it working on my swarm on openstack. Really appreciate all the amazing work!
