### ISSUE TITLE
Failover https endpoint for ScaleIO

### ISSUE THREAD

**Issue by clubanderson** [codedellemc/rexray#813]
# Summary
I have rexray configured to point at a single EMC scaleio manager. I have 2 managers and a tie breaker for scaleio. If the main manager goes down, rex ray can’t find the backup. I don’t think i can specify more than one endpoint for rex ray for this type of failover, can I?

## Version
Please paste the output of `rexray version`. For example:

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.8.1
OsArch: Linux-x86_64
Branch: v0.8.1
Commit: 30e9082
Formed: Fri, 24 Feb 2017 21:00:28 CST

libStorage
----------
SemVer: 0.5.1
OsArch: Linux-x86_64
Branch: v0.8.1
Commit: 35c7b6d96d5f17aa0c0379924615ae22c1ad3d45
Formed: Fri, 24 Feb 2017 20:59:00 CST
```

## Expected Behavior
If a scaleio MDM fails to respond, the failover MDM will be contacted to do the necessary task.

## Actual Behavior
There is no way to follow failover of MDM's

## Steps To Reproduce
Configure rexray to point at a scaleio MDM.  Stop the MDM service on that endpoint

## Configuration Files
Please paste any related configuration files, such as `/etc/rexray/config.yml`
in this section. Please use the appropriate formatting when pasting YAML.
content. For example:

```libstorage:
  server:
    services:
      scaleio:
        driver: scaleio
        scaleio:
          endpoint: https://10.183.16.118/api
          thinOrThick: ThinProvisioned
          insecure: true
          userName: admin
          password: ------
          systemName: help1
          protectionDomainName: protection_domain_help
          storagePoolName: help_pool```

**Comment by kacole2** [comment]
@clubanderson i believe you opened this prior issue and it was answered. was this not the case? https://github.com/codedellemc/rexray/issues/772#issuecomment-286226094

**Comment by clubanderson** [comment]
Ahh, yes it is - please close this - i didn’t see the reply

**Comment by kacole2** [comment]
no problem @clubanderson. some of these questions may be better suited in our Slack Channel and leave GitHub to bug reports. please join us in the #project-rexray channel http://community.codedellemc.com/
