### ISSUE TITLE
Docker resize volume

### ISSUE THREAD

**Issue by tumanh** [codedellemc/rexray#823]
# Summary
I using rexray, docker plugin rexray/scaleio and mesos/marathon to deploy apps. But a can't resize volume docker container. For example: 
Step1: default, I configure size : 100GB

```
root@mesos-192-168-6-113:/home/manhnv# docker run -itd --volume-driver=rexray -v test:/tmp nginx
2d71c3eae38f710acdd21b65aac536653551daee777cda2dab54ea3a99b71805
root@mesos-192-168-6-113:/home/manhnv# lsblk 
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 894.3G  0 disk 
├─sda1   8:1    0   976M  0 part /boot
├─sda2   8:2    0     1K  0 part 
├─sda5   8:5    0  29.8G  0 part [SWAP]
└─sda6   8:6    0 863.5G  0 part /
sdb      8:16   0 894.3G  0 disk 
└─sdb1   8:17   0 894.3G  0 part /data
sdc      8:32   0 894.3G  0 disk 
└─sdc1   8:33   0 894.3G  0 part /data1
scinia 251:0    0   104G  0 disk /var/lib/libstorage/volumes/test
```

Step2: Stop container (100gb), and resize volume by ScaleIO GUI, 100gb --->200GB
Step3: Restart container
Step4: Checking "lsblk" 
```
root@mesos-192-168-6-113:/home/manhnv# lsblk 
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0 894.3G  0 disk 
├─sda1   8:1    0   976M  0 part /boot
├─sda2   8:2    0     1K  0 part 
├─sda5   8:5    0  29.8G  0 part [SWAP]
└─sda6   8:6    0 863.5G  0 part /
sdb      8:16   0 894.3G  0 disk 
└─sdb1   8:17   0 894.3G  0 part /data
sdc      8:32   0 894.3G  0 disk 
└─sdc1   8:33   0 894.3G  0 part /data1
scinia 251:0    0   200G  0 disk /var/lib/libstorage/volumes/test
```

But container check 'df -h ':
```
root@mesos-192-168-6-113:/home/manhnv# docker exec -it 2d71c3eae38f bash 
root@2d71c3eae38f:/# df -h
Filesystem                                              Size  Used Avail Use% Mounted on
none                                                    850G   68G  739G   9% /
tmpfs                                                    48G     0   48G   0% /dev
tmpfs                                                    48G     0   48G   0% /sys/fs/cgroup
/dev/scinia                                             103G   60M   97G   1% /tmp
```
I wanna /dev/scinia has 200gb

**Comment by kacole2** [comment]
@tumanh i've gone ahead and cleaned up the markdown formatting for your request.

Today, REX-Ray doesn't have the feature to extend/expand disk partitions. Your process is correct, but you will have to go into the container and issue the commands necessary for your container to resize it based upon the OS used in your container image.

please close this issue if this answered your question

**Comment by clintonskitson** [comment]
@tumanh There are multiple expansions that need to take place. A `df` looks at the space as reported by a filesystem. A `lsblk` looks at the raw block device size. So you have a raw block device that has grown and is recognized, but you have not grown the filesystem. 

Assuming it's ext4, run `resize2fs /dev/scsinia` followed by `e2fsck /dev/scinia`.

**Comment by tumanh** [comment]
@clintonskitson Thank but  I try
`e2fsck /dev/scinia      
e2fsck 1.43.4 (31-Jan-2017)
/dev/scinia is mounted.



WARNING!!!  The filesystem is mounted.   If you continue you ***WILL***
cause ***SEVERE*** filesystem damage.


Do you really want to continue<n>? yes
e2fsck: No such file or directory while trying to open /dev/scinia
Possibly non-existent device?
`
and try 
'root@2d71c3eae38f:/# resize2fs /dev/scsinia 200gb
resize2fs 1.43.4 (31-Jan-2017)
open: No such file or directory while opening /dev/scsinia'

**Comment by tumanh** [comment]
@kacole2  Thank you !! I Next time I will write more clearly

**Comment by clintonskitson** [comment]
Ok, a couple of basic things.. 1) Make sure the filesystem is not mounted 2) Make sure the device is actually attached. You can use the `rexray attach` command to just make the device present. From there the commands specified should work if you are using the path that gets returned from REX-Ray.

**Comment by codenrhoden** [comment]
Going to close this for now. Feel free to re-open if more guidance is needed.

**Comment by yuklia** [comment]
@codenrhoden i have the same issue
