### ISSUE TITLE
Specifying volume size in docker compose file

### ISSUE THREAD

**Issue by skuppa** [codedellemc/rexray#828]
I have installed the docker plugin for `rexray/ebs` and it works awesome with docker stack.  By default, it creates 16GB volume and I would like to change the size depends on my stack.  I am able to create the docker volume with different size using cli but I am not able to leverage the size options in the compose file and it looks like the `version 3` don't support  options param.  What is the right way to pass the options param to the `rexray/ebs` plugin via volume specification in the compose file?

The following cli works
```
docker volume create --driver=rexray/ebs --opt=size=5 --name=volume-test-cli
```

The below compose file throws error `options Additional property options is not allowed`
```
version: '3'

# docker stack deploy --with-registry-auth --compose-file volume-test.yml volume-test

services:
  test-proxy:
    image: busybox
    volumes:
      - test-data-volume:/test
volumes:
  test-data-volume: 
    driver: rexray/ebs
    options: 
      size: 5
```

**Comment by Routhinator** [comment]
I suspect the answer to your question is this:

```yaml
version: '3'

volumes:
  test-data-volume:
    driver: rexray
    driver_opts:
      size: 1
```

This is how driver options are passed to the docker-volume-netshare NFS driver via compose. 

I wanted to verify this before replying but I just hit the DO underscore bug (https://github.com/codedellemc/libstorage/issues/450) And I cannot test this as I need to create my volumes manually for now.

**Comment by codenrhoden** [comment]
Closing this for now, as I believe @Routhinator answered the question correctly.

As an aside, @Routhinator I hope you also saw that it should be possible to have REX-Ray deal with those DO underscores now.
