### ISSUE TITLE
How to build rexray docker-plugin on dev

### ISSUE THREAD

**Issue by sebglon** [codedellemc/rexray#855]
# Summary
In this doc [build-reference](https://rexray.readthedocs.io/en/stable/dev-guide/build-reference/), i can build rexray from source. But how to build docker-plugin?

this cmd `DRIVERS="cinder" make docker-build` not run task `build-docker-plugin`
i have `Make: *** No rule to build the build-docker-plugin target. Stop.`

I run this on master branch

**Comment by clintkitson** [comment]
Make sure you have Go installed locally. It is currently needed to build
the plugins.

**Comment by sebglon** [comment]
ok it's that; but why do not reuse task docker-build if docker is installed?

**Comment by clintkitson** [comment]
The goal is to minimize the dependencies needed to build so having Go installed on the local system definitely isn't ideal. It has been discussed and we should remove that dependency in an upcoming release.

**Comment by akutz** [comment]
Hi @sebglon,

If you want to clone the `release/0.9.1` branch it has a file called `build.sh` that should provide the solution you're requesting.

- https://github.com/codedellemc/rexray/pull/846
- https://github.com/codedellemc/rexray/pull/848
- https://gist.github.com/akutz/15e7d6610196fb885a015646824112ad

**Comment by akutz** [comment]
Hi @sebglon,

One note, the `build.sh` file requires >=Docker 17.5 as I decided to take advantage of Docker's new multistage build system introduced in 17.5.

**Comment by akutz** [comment]
Hi @sebglon,

FYI, while the `build.sh` command is something I messed around with last week, before that I did actually fix the `Makefile` so that it didn't need to depend on Go for building REX-Ray plug-ins if Docker was present. You could cherry-pick 5d6427db7258f4e20eb4adec324d70c0dd5acc37 for that change.

**Comment by sebglon** [comment]
thanks very nice.
i test it

**Comment by sebglon** [comment]
It work fine thanks.
