### ISSUE TITLE
[K8s] FlexVolume plugin not working properly

### ISSUE THREAD

**Issue by mabounassif** [codedellemc/rexray#864]
# Summary
Greetings folks! I have a question about FlexVolumes with kuberlet v1.6.3. I'm running kubelet with the following flag `--enable-controller-attach-detach=false` and I'm using the `flexrex` driver  which I setup in the following directory: `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/rexray~flexrex/flexrex`. I'm *NOT* getting the log `plug-ins.go:350] Loaded volume plug-in "rexray/flexrex"` and volumes are not being mounted :cry: Please point me to the right direction. Thanks!

## Version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0+10
OsArch: Linux-x86_64
Branch: release/0.9.1
Commit: b9066f16a125c85b1ae479ef5439b6869cca1d25
Formed: Thu, 18 May 2017 16:47:41 UTC

libStorage
----------
SemVer: 0.6.0
OsArch: Linux-x86_64
Branch: (detached from fa055d6
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9
Formed: Thu, 18 May 2017 16:44:42 UTC

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.7.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a20a838ca70838a914b632637398824fcb10d0db
Formed: Mon, 23 Jan 2017 10:14:32 EST

libStorage
----------
SemVer: 0.4.0
OsArch: Linux-x86_64
Branch: v0.7.0
Commit: a1103d3f215117f7b9f51dae2b24f852c9c54995
Formed: Mon, 23 Jan 2017 10:14:12 EST
```

## Expected Behavior
Expecting `plug-ins.go:350] Loaded volume plug-in "rexray/flexrex"` in the logs and volumes to successfully mount to pods.

## Actual Behavior
`plug-ins.go:350] Loaded volume plug-in "rexray/flexrex"` missing from logs and pods fail with timeout volume mounts

## Steps To Reproduce
Deploy a pod that claims a volume using the flex driver

**Comment by codenrhoden** [comment]
Hi @mabounassif,

Well you are doing the right thing by looking for that `plugin-ins.go` line in the logfile first. That being missing means that that the kubelet is definitely not picking up on the the FlexVolume driver.

You said that you "setup" the driver in `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/rexray~flexrex/flexrex`. May I ask how you did that? Did you create something in there yourself? Or did you use `rexray flexrex install` ?

Could you paste the output of `rexray scripts list`, please?

Also, I am confused by the text of the original Issue report, specifically about the version(s) involved. Can you edit that section to juse show the output of the `rexray version` command? Right now it shows what appears to be a custom build of REX-Ray (are you building from master?), and then also shows REX-Ray 0.7.0. So I'm not sure what to think, there. I suspect you left in the example from the Issue template, but I can't be sure.

**Comment by mabounassif** [comment]
I had the improper log level I've added `-v 5` when executing Kubelet.
I was able to debug further and resolved a setup issue: I needed to add the Rexray config yaml file instead of relying on environment variables that were not getting sourced by the flex plugin bash.

It works great now.
