### ISSUE TITLE
Docker volume plugin fails to mount EBS on Amazon Linux

### ISSUE THREAD

**Issue by toddschilling** [codedellemc/rexray#867]
# Summary
`docker run` returns an error when trying to bind to an EBS volume on Amazon Linux

# Bug Reports
```shell
$ docker run --rm -it -v rexray-proof-amzn:/data --volume-driver=ebs alpine sh
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/var/lib/libstorage/volumes/rexray-proof-amzn/data\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper/mnt/bdf1878eccb1bf7970d9fc91b757c00bbb65ec78a4fd2a15e15fa2d00ba8e14a/rootfs\\\\\\\" at \\\\\\\"/data\\\\\\\" caused \\\\\\\"stat /var/lib/libstorage/volumes/rexray-proof-amzn/data: no such file or directory\\\\\\\"\\\"\"\n".
```

## Version
```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: 2a7458dd90a79c673463e14094377baf9fc8695e
Formed: Wed, 03 May 2017 21:38:11 UTC

libStorage
----------
SemVer: 0.6.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9
Formed: Wed, 03 May 2017 21:36:11 UTC
```

```shell
$ docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Tue Mar  7 20:34:04 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   7392c3b/1.12.6
 Built:        Tue Mar  7 20:34:04 2017
 OS/Arch:      linux/amd64
```

## Expected Behavior
On Ubuntu, using the same IAM role, security group, subnet, etc, the volume is mounted without error.

## Steps To Reproduce

1.  Launch a new instance of `amzn-ami-hvm-2017.03.0.20170417-x86_64-gp2 (ami-4836a428)` in us-west-2.
2.  Set the IAM Role Policy to have the following actions:
      "ec2:AttachVolume",
      "ec2:CreateVolume",
      "ec2:CreateSnapshot",
      "ec2:CreateTags",
      "ec2:DeleteVolume",
      "ec2:DeleteSnapshot",
      "ec2:DescribeAvailabilityZones",
      "ec2:DescribeInstances",
      "ec2:DescribeVolumes",
      "ec2:DescribeVolumeAttribute",
      "ec2:DescribeVolumeStatus",
      "ec2:DescribeSnapshots",
      "ec2:CopySnapshot",
      "ec2:DescribeSnapshotAttribute",
      "ec2:DetachVolume",
      "ec2:ModifySnapshotAttribute",
      "ec2:ModifyVolumeAttribute",
      "ec2:DescribeTags"
3.  Install docker
     `sudo yum update -y && sudo yum install -y docker && service docker start`
4.  Install REX-Ray
     `curl -sSL https://dl.bintray.com/emccode/rexray/install | sh`
5.  Configure REX-Ray with the configuration file below.
6.  Start REX-Ray
     `rexray service start`
7.  Create an EBS volume
     `docker volume create --driver=ebs --name=myvolume --opt size=1 --opt volumeType=gp2`
8.  Run a docker container with a bind-mount to the new EBS volume
     `docker run --rm -it -v myvolume:/data --volume-driver=ebs alpine sh`

## Configuration Files

```yaml
rexray:
  modules:
    default-docker:
      disabled: true
    ebs-docker:
      type:     docker
      host:     unix:///run/docker/plugins/ebs.sock
      spec:     /etc/docker/plugins/ebs.spec
      libstorage:
        service: ebs
libstorage:
  server:
    services:
      ebs:
        driver: ebs
```

### Service Log
```shell
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: 2a7458dd90a79c673463e14094377baf9fc8695e
Formed: Wed, 03 May 2017 21:38:11 UTC

libStorage
----------
SemVer: 0.6.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9
Formed: Wed, 03 May 2017 21:36:11 UTC
```

### Client Log
```shell
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:359: container init caused \\\"rootfs_linux.go:53: mounting \\\\\\\"/var/lib/libstorage/volumes/rexray-proof-amzn/data\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/devicemapper/mnt/942ee36528b1a167ce0746759e4dd504f11f948c94a5e9143a7ae889e0643073/rootfs\\\\\\\" at \\\\\\\"/data\\\\\\\" caused \\\\\\\"stat /var/lib/libstorage/volumes/rexray-proof-amzn/data: no such file or directory\\\\\\\"\\\"\"\n".
```

**Comment by toddschilling** [comment]
After more research and issue searches, I found the resolution [here](https://github.com/codedellemc/rexray/issues/510).

**Comment by clintkitson** [comment]
Thanks @toddschilling
