### ISSUE TITLE
Suggestion: Add S3 Bucket as Volume Storage

### ISSUE THREAD

**Issue by tomfarnham** [codedellemc/rexray#87]
Honestly, I don't even know if this is feasible, but I thought it would be useful if you could mount an S3 bucket directly as a volume. There already exists the s3-fuse file system: https://github.com/s3fs-fuse/s3fs-fuse

**Comment by akutz** [comment]
Hi @tomfarnham,

So fuse is a user-land file system driver meant to add FS support for FS types not supported by the kernel. I have written a few extensions to MacFuse for the Mach (Darwin/OS X) kernel myself. This *should* be feasible, and if you'd like to fork the project to add the beginnings of a fuse driver, feel free. Otherwise we'll take this into consideration as having a fuse driver would greatly expand support for different storage and file systems.

**Comment by tomfarnham** [comment]
Hi @akutz,

Unfortunately, this is not in the realm of my ability or I would attempt it. Thank you for considering it.

**Comment by clintonskitson** [comment]
Hey @tomfarnham, thanks for the request.  I agree here, a fuse driver would be a very valuable addition to RR.  We will track it as an enhancement request.

**Comment by nnordrum** [comment]
Would also be super helpful if you could have it restore from the s3 backup if it doesn't exist locally (i.e. like `docker pull` does when you don't have an image). I'm not sure on the semantics of how this would work, but would be very helpful in a very wide environment.

**Comment by clintonskitson** [comment]
Hello @nnordrum.  In relation to EC2 and EBS, the snapshots of volumes are held within S3 natively.  With RR today, you can already create a snapshot which on the backend gets sent to S3.  From there you can choose to create a volume from an existing snapshot which again from the backend pulls it from S3.

Is this similar to what you were thinking?

The discussion here though is focused on building a FUSE driver which would enable a bunch of different use cases but slightly different from simply being able to do backup/restore (snapshot/create volume from snapshot).

**Comment by nnordrum** [comment]
Exactly what I was thinking. Does it have to be done separately, or can that be done as part of the `docker run` command? e.g.
```
(obviously pseudo code)
docker run --volume-driver=rexray -v something:/something -e RESTORE_FROM=http://somewhere busybox bash
or (more ideally, but not supported)
docker run --volume-driver=rexray -v something:/something --vol-opts "RESTORE_FROM=http://somewhere" busybox bash
```
Apparently you can't pass parameters into the volume driver, so I made up the -e, since i knew that would work...

**Comment by nnordrum** [comment]
additionally, might I suggest the issue is renamed to something like "Suggestion: Add Fuse Driver Support for Volume Storage"

**Comment by clintonskitson** [comment]
Currently, the `docker run` command does not allow extra options for volumes.  These are done via the `docker volume` command.  So in this case you could do (1.9) `docker volume create --driver=rexray --opt=snapshotid=actualsnapshotid --name=newvolumename`.  Following this you would use the volume as `docker run --volume-driver=rexray -v newvolumename:/test busybox`.

Let me know, and thanks for the feedback.
