### ISSUE TITLE
[ERROR] Update failed for cloud.google.com/go: Cannot detect VCS

### ISSUE THREAD

**Issue by Nayana-ibm** [codedellemc/rexray#870]
I am trying to build Rex-Ray from source on Ubuntu platform.
on make command getting below error:
`[ERROR] Failed to set version on cloud.google.com/go to e4de3dc4493f142c5833f3185e1182025a61f805: open /go/src/github.com/codedellemc/rexray/vendor/cloud.google.com/go:file or directory`

Steps to reproduce:
```
git clone https://github.com/codedellemc/rexray
cd rexray
git checkout v0.9.0
make
```

**Comment by akutz** [comment]
Hi @Nayana-ibm,

Were you cloning REX-Ray inside of the `GOPATH` by chance? Also, the above error isn't related to REX-Ray but rather its dependency management tool `glide`. Sometimes network errors occur during a `glide` operation, resulting in a bad dependency pull. 

Ensure that you're cloning REX-Ray inside the proper location and then try again.

**Comment by clintkitson** [comment]
Another one to check here is whether you have Docker installed on the host. If so, then it will not require dependencies locally since it builds all from within a container.

**Comment by akutz** [comment]
To clarify, it won't require build tool dependencies. It will still download the sources of the Go projects on which it depends. This step happens with or without Docker, and that's why I mentioned the possible network issues.

**Comment by akutz** [comment]
Hi @clintkitson,

Was on mobile. The reason I added the above clarification was because the nature of this issue is regarding dependencies. I wanted to make clear that the dependencies you mentioned were of the Build Toolchain variety and the dependencies @Nayana-ibm is discussing are the Go source dependencies which get downloaded via the build process regardless of whether or not Docker is used to run the build.

**Comment by Nayana-ibm** [comment]
@akutz Thanks for your inputs. 
I have cloned the code again, tried running make and it worked!

I have also came across [this ](https://github.com/Masterminds/glide/issues/612)issue where replacing 
```
- name: cloud.google.com/go
  version: e4de3dc4493f142c5833f3185e1182025a61f805
```
with
```
- name: cloud.google.com/go
  version: 9c1098a4debc9bf1073ed0e4872b12bd916243d8
```
solves the issue.
