### ISSUE TITLE
How to implement automatically quota for rexray/rbd?

### ISSUE THREAD

**Issue by JinsYin** [codedellemc/rexray#872]
- **Manually create volumes and run:** (working)
```
docker volume create --driver rexray --opt=size=10 --name nginx_data
docker run -it --name web -p 8000:80 --volume-driver=rexray -v nginx_data:/usr/share/nginx -d nginx:1.11.9-alpine
```

- **Automatically quota** (error)
```docker run -it --name web -p 8000:80 --volume-driver=rexray -v nginx_data_2:/usr/share/nginx --storage-opt=size=10 -d nginx:1.11.9-alpine```
  
  > Error response from daemon: --storage-opt is not supported for overlay

**Comment by clintkitson** [comment]
The error is a Docker error relating to the graph driver which is storae
for the container image itself. This is showing in its reference to
"overlay." REX-Ray is not related to this error.

**Comment by JinsYin** [comment]
Thank you. It's working when I try use devicemapper driver.
