### ISSUE TITLE
REX-Ray can't create a new volume on Isilon

### ISSUE THREAD

**Issue by kimiya07** [codedellemc/rexray#890]
Hi, 

Currenly, I am trying to configure REX-Ray with Isilon. Now, REX-Ray service has seemingly started normally with the command "rexray start"
When I list rexray volume, it shows a result like below.
<pre>
[root@sunny ~]# rexray volume ls
ID                          Name                        Status     Size
test_at_isilon_ifs_volumes  test_at_isilon_ifs_volumes  available  0
</pre>
Here, test_at_isilon_ifs_volumes was created when I started REX-Ray service for the first time.

However, when I try to create a new volume with the following command, it fails
<pre>
[root@sunny ~]# rexray volume create rexray_isilon_1 --size=20
FATA[0000] error creating volume                         error.inner.resourceID="rexray_isilon_1" error.status=404 volume=rexray_isilon_1
</pre>

I put the debug log of this volume create operation at the bottom of this post.
Please investigate through it.
I am very new to Isilon, so this ERROR may be related to Isilon configuration. But I don't know what is wrong at all.
So I hope I can get through this with your help.

## Version
<pre>
[root@sunny ~]# rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: 2a7458dd90a79c673463e14094377baf9fc8695e
Formed: Thu, 04 May 2017 06:38:11 JST

libStorage
----------
SemVer: 0.6.0
OsArch: Linux-x86_64
Branch: v0.9.0
Commit: fa055d6da595602715bdfd5541b4aa6d4dcbcbd9
Formed: Thu, 04 May 2017 06:36:11 JST
</pre>

## Configuration Files
<pre>
[root@sunny ~]# cat /etc/rexray/config.yml
libstorage:
  service: isilon
isilon:
  endpoint: https://192.168.20.40:8080
  group: wheel
  username: root
  password: password
  volumePath: /ifs/volumes
  nfsHost: 192.168.20.40
  dataSubnet: 192.168.20.0/24
  insecure: true
</pre>

### Debug Log
<pre>
[root@sunny ~]# rexray volume create rexray_isilon_1 --size=20 -l debug
INFO[0000] updated log level                             logLevel=debug
DEBU[0000] os.args                                       time=1497516974875 val=[rexray volume create rexray_isilon_1 --size=20 -l debug]
DEBU[0000] activating libStorage                         cmd=create time=1497516974875
DEBU[0000] parseSafeHost - no change                     postParse=unix:///var/run/libstorage/006419894.sock preParse=unix:///var/run/libstorage/006419894.sock time=1497516974877
DEBU[0000] read spec file                                host=unix:///var/run/libstorage/006419894.sock path=/var/run/rexray/rexray.spec time=1497516974877
DEBU[0000] is local unix server active                   sock=/var/run/libstorage/006419894.sock time=1497516974877
DEBU[0000] set host in context                           host=unix:///var/run/libstorage/006419894.sock time=1497516974878
DEBU[0000] set host in config                            host=unix:///var/run/libstorage/006419894.sock time=1497516974878
DEBU[0000] not starting embedded server; already running  host=unix:///var/run/libstorage/006419894.sock time=1497516974878
DEBU[0000] creating libStorage client                    cmd=create host=unix:///var/run/libstorage/006419894.sock time=1497516974878
DEBU[0000] created scoped scope                          new=libstorage.client parentScopes=rexray,
INFO[0000] configured logging                            host=unix:///var/run/libstorage/006419894.sock libstorage.logging.httpRequests=false libstorage.logging.httpResponses=false libstorage.logging.level=debug time=1497516974930
DEBU[0000] got configured host address                   host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516974937
DEBU[0000] getHost proto == "unix"                       getHost=libstorage-server host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516974939
INFO[0000] created libStorage client                     clientType=integration disableKeepAlive=false enableInstanceIDHeaders=true enableLocalDevicesHeaders=true host=unix:///var/run/libstorage/006419894.sock lAddr=libstorage-server logRequests=false logResponses=false lsxMutexPath=/var/run/libstorage/lsx.lock lsxPath=/var/lib/libstorage/lsx-linux service=isilon storageDriver=libstorage time=1497516974950
INFO[0000] registered custom context key                 externalID=Libstorage-Tx internalID=2 keyBitmask=2
INFO[0000] registered custom context key                 externalID=Libstorage-Instanceid internalID=3 keyBitmask=2
INFO[0000] registered custom context key                 externalID=Libstorage-Localdevices internalID=4 keyBitmask=2
INFO[0000] registered custom context key                 externalID=Authorization internalID=5 keyBitmask=2
DEBU[0000] successful connection                         host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516974951
INFO[0000] initializing executors cache                  host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516974957
DEBU[0000] updating executor                             host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516974959
DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516974959
DEBU[0000] executor exists, getting local checksum       host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516974960
DEBU[0000] getting executor checksum                     host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516974960
DEBU[0000] got local executor checksum                   host=unix:///var/run/libstorage/006419894.sock localChecksum=55741970708ecf145f6af884a86407aa service=isilon storageDriver=libstorage time=1497516974988
DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516974988
INFO[0000] initializing supported cache                  host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516974988
DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516974989 txCR=1497516974 txID=78883e58-1dce-4ce4-4507-b0eacd44f79e
DEBU[0000] invoking executor cli                         args=[isilon supported] cmd=/var/lib/libstorage/lsx-linux host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516974989 txCR=1497516974 txID=78883e58-1dce-4ce4-4507-b0eacd44f79e
DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975099 txCR=1497516974 txID=78883e58-1dce-4ce4-4507-b0eacd44f79e
DEBU[0000] cached supported flag                         host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage supported=15 time=1497516975100 txCR=1497516974 txID=78883e58-1dce-4ce4-4507-b0eacd44f79e
INFO[0000] initializing instance ID cache                host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975100
DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975100 txCR=1497516975 txID=beb8dfc6-5a0e-496c-74d3-cbaebca981d4
DEBU[0000] invoking executor cli                         args=[isilon instanceID] cmd=/var/lib/libstorage/lsx-linux host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975100 txCR=1497516975 txID=beb8dfc6-5a0e-496c-74d3-cbaebca981d4
DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975203 txCR=1497516975 txID=beb8dfc6-5a0e-496c-74d3-cbaebca981d4
DEBU[0000] sending instanceID in API.InstanceInspect call  host=unix:///var/run/libstorage/006419894.sock instanceID=isilon=,,WyIxMjcuMC4wLjEvOCIsIjEwLjMyLjIuNTUvMjQiLCIxNzIuMTYuNS4xLzI0IiwiMTcyLjE4LjAuMS8xNiIsIjE3Mi4xNy4wLjEvMTYiLCIxOTIuMTY4LjIwLjIxMi8yNCIsIjo6MS8xMjgiLCJmZTgwOjoyNTA6NTZmZjpmZWJiOjJlZDcvNjQiLCJmZTgwOjoyNTA6NTZmZjpmZWJiOjIzYTAvNjQiLCJmZTgwOjo0Mjo4YWZmOmZlYzk6YzQ2My82NCIsImZlODA6OmY0N2U6NDZmZjpmZTI0OjJiMTQvNjQiLCJmZTgwOjoyNTA6NTZmZjpmZWJiOmM5ZjcvNjQiXQ== server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975203 txCR=1497516975 txID=beb8dfc6-5a0e-496c-74d3-cbaebca981d4
DEBU[0000] received instanceID from API.InstanceInspect call  host=unix:///var/run/libstorage/006419894.sock instanceID=isilon=,,WyIxMjcuMC4wLjEvOCIsIjEwLjMyLjIuNTUvMjQiLCIxNzIuMTYuNS4xLzI0IiwiMTcyLjE4LjAuMS8xNiIsIjE3Mi4xNy4wLjEvMTYiLCIxOTIuMTY4LjIwLjIxMi8yNCIsIjo6MS8xMjgiLCJmZTgwOjoyNTA6NTZmZjpmZWJiOjJlZDcvNjQiLCJmZTgwOjoyNTA6NTZmZjpmZWJiOjIzYTAvNjQiLCJmZTgwOjo0Mjo4YWZmOmZlYzk6YzQ2My82NCIsImZlODA6OmY0N2U6NDZmZjpmZTI0OjJiMTQvNjQiLCJmZTgwOjoyNTA6NTZmZjpmZWJiOmM5ZjcvNjQiXQ== server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975208 txCR=1497516975 txID=beb8dfc6-5a0e-496c-74d3-cbaebca981d4
DEBU[0000] cached instanceID                             host=unix:///var/run/libstorage/006419894.sock instanceID=isilon:isilon=192.168.20.212 server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975208 txCR=1497516975 txID=beb8dfc6-5a0e-496c-74d3-cbaebca981d4
DEBU[0000] xli instanceID success                        host=unix:///var/run/libstorage/006419894.sock instanceID=isilon:isilon=192.168.20.212 server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975209 txCR=1497516975 txID=beb8dfc6-5a0e-496c-74d3-cbaebca981d4
INFO[0000] successefully dialed libStorage server        host=unix:///var/run/libstorage/006419894.sock server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975209
INFO[0000] storage driver initialized                    host=unix:///var/run/libstorage/006419894.sock service=isilon storageDriver=libstorage time=1497516975209
INFO[0000] os driver initialized                         host=unix:///var/run/libstorage/006419894.sock osDriver=linux service=isilon storageDriver=libstorage time=1497516975214
INFO[0000] linux integration driver successfully initialized  host=unix:///var/run/libstorage/006419894.sock integrationDriver=linux libstorage.integration.volume.operations.create.default.IOPS=0 libstorage.integration.volume.operations.create.default.availabilityZone= libstorage.integration.volume.operations.create.default.fsType=ext4 libstorage.integration.volume.operations.create.default.size=16 libstorage.integration.volume.operations.create.default.type= libstorage.integration.volume.operations.create.implicit=true libstorage.integration.volume.operations.mount.path=/var/lib/libstorage/volumes libstorage.integration.volume.operations.mount.rootPath=/data osDriver=linux service=isilon storageDriver=libstorage time=1497516975239
INFO[0000] path cache initializion disabled              host=unix:///var/run/libstorage/006419894.sock integrationDriver=linux osDriver=linux service=isilon storageDriver=libstorage time=1497516975245
INFO[0000] libStorage integration driver successfully initialized  host=unix:///var/run/libstorage/006419894.sock integrationDriver=linux libstorage.integration.volume.operations.create.disable=false libstorage.integration.volume.operations.mount.preempt=false libstorage.integration.volume.operations.path.cache.async=true libstorage.integration.volume.operations.path.cache.enabled=false libstorage.integration.volume.operations.remove.disable=false libstorage.integration.volume.operations.unmount.ignoreusedcount=false osDriver=linux service=isilon storageDriver=libstorage time=1497516975257
INFO[0000] integration driver initialized                host=unix:///var/run/libstorage/006419894.sock integrationDriver=linux osDriver=linux service=isilon storageDriver=libstorage time=1497516975257
INFO[0000] created libStorage client                     host=unix:///var/run/libstorage/006419894.sock integrationDriver=linux osDriver=linux service=isilon storageDriver=libstorage time=1497516975257
DEBU[0000] waiting on executor lock                      host=unix:///var/run/libstorage/006419894.sock instanceID=isilon:isilon=192.168.20.212 integrationDriver=linux osDriver=linux server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975257 txCR=1497516975 txID=3f8568f3-2b83-4bce-4992-feba8d364f58
DEBU[0000] invoking executor cli                         args=[isilon localDevices quick] cmd=/var/lib/libstorage/lsx-linux host=unix:///var/run/libstorage/006419894.sock instanceID=isilon:isilon=192.168.20.212 integrationDriver=linux osDriver=linux server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975257 txCR=1497516975 txID=3f8568f3-2b83-4bce-4992-feba8d364f58
DEBU[0000] signalling executor lock                      host=unix:///var/run/libstorage/006419894.sock instanceID=isilon:isilon=192.168.20.212 integrationDriver=linux osDriver=linux server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975379 txCR=1497516975 txID=3f8568f3-2b83-4bce-4992-feba8d364f58
DEBU[0000] xli localdevices success                      host=unix:///var/run/libstorage/006419894.sock instanceID=isilon:isilon=192.168.20.212 integrationDriver=linux osDriver=linux server=vanilla-wanderer-aq service=isilon storageDriver=libstorage time=1497516975379 txCR=1497516975 txID=3f8568f3-2b83-4bce-4992-feba8d364f58
DEBU[0000] built output template                         host=unix:///var/run/libstorage/006419894.sock template={{define "printVolumeWithPathFields"}}{{.ID}}  {{.Name}}       {{.Volume.AttachmentState | printAttState}}  {{.Size}}       {{.Path}}{{end}}{{define "printEncVolumeWithPathFields"}}{{.ID}}        {{.Name}}       {{.Volume.AttachmentState | printAttState}}     {{.Size}}    {{.Encrypted}}  {{.Path}}{{end}}{{define "printSnapshotFields"}}{{.ID}} {{.Name}}       {{.Status}}     {{.VolumeID}}{{end}}{{define "printScriptFields"}}{{.Path}}     {{.Installed}}       {{.Modified}}{{end}}{{define "printAuthTokenFields"}}{{.Subject}}       {{.IssuedAt}}   {{.NotBefore}}  {{.Expires}}{{end}}{{define "printStringSlice"}}{{.}}{{end}}{{define "printJSON"}}{{. | json}}{{end}}{{define "printVolumeID"}}{{.ID}}{{end}}{{define "printInstanceFields"}}{{.InstanceID.ID}}      {{.Name}}       {{.ProviderName}}       {{.Region}}{{end}}{{define "printMountFields"}}{{.ID}}       {{.Source}}     {{.MountPoint}}{{end}}{{define "printObject"}}{{printf "%v" .}}{{end}}{{define "printPrettyJSON"}}{{. | jsonp}}{{end}}{{define "printVolumeFields"}}{{.ID}}  {{.Name}}       {{.AttachmentState | printAttState}}    {{.Size}}{{end}}{{define "printEncVolumeFields"}}{{.ID}}        {{.Name}}       {{.AttachmentState | printAttState}}{{.Size}}        {{.Encrypted}}{{end}}{{define "printServiceFields"}}{{.Name}}   {{.Driver.Name}}{{end}}{{range .D }}{{template "printObject" .}}
{{end}} time=1497516975398
FATA[0000] error creating volume                         error.inner.resourceID="rexray_isilon_1" error.status=404 volume=rexray_isilon_1
</pre>

**Comment by codenrhoden** [comment]
Hi @kimiya07,

Yes, this was a [regression](https://github.com/codedellemc/libstorage/issues/556) with REX-Ray 0.9.0. 0.9.1 was [released last Friday](https://github.com/codedellemc/rexray/releases/tag/v0.9.1) to address this very problem (among others). So it should be fixed in the latest release.

**Comment by kimiya07** [comment]
Thanks a lot, @codenrhoden !
