### ISSUE TITLE
Ceph rbd volume is always unavailable in multi machine?

### ISSUE THREAD

**Issue by JinsYin** [codedellemc/rexray#895]
I'm using the calico network to deploy HDFS clusters and Cassandra clusters in marathon, and I used rexray ceph/rbd driver. Them can work normally when I first deployed them.

I tried to switch the calico network, then marathon will automatically restart all application. But, some rbd volume are always `unavailable`.

## Marathon ui
Cassandra  
![cassandra](https://user-images.githubusercontent.com/12714609/27249460-a7615eaa-5348-11e7-9022-4e36c1d64eee.png)

HDFS  
![hdfs](https://user-images.githubusercontent.com/12714609/27249462-b030b314-5348-11e7-9ad8-ce52f77306b9.png)

## Mesos log

```
/usr/bin/docker-current: Error response from daemon: VolumeDriver.Mount: {"Error":"resource not found"}.
```

## Rexray log

In addition to the volume unavailable, many volumes with random ID are created?
```
docker.bf2e53a2d1d163449aed8c9d4c707247a326c25456ddeb7f671a0dca84be0477  bf2e53a2d1d163449aed8c9d4c707247a326c25456ddeb7f671a0dca84be0477  available    16
docker.bf403e33a5b1ff0cc3d2befbaeea531b82ac8e91dfe5157608daa1dbc9ce1071  bf403e33a5b1ff0cc3d2befbaeea531b82ac8e91dfe5157608daa1dbc9ce1071  available    16
docker.c17e8365fd9c375937f99eddd40b153b0185609e70b424263e685dd841d9911c  c17e8365fd9c375937f99eddd40b153b0185609e70b424263e685dd841d9911c  available    16
docker.c4fa07a2f7725b0b8e1c6a0837b6b263efabbfe6bfaa6272d7a61ec2662b6a4c  c4fa07a2f7725b0b8e1c6a0837b6b263efabbfe6bfaa6272d7a61ec2662b6a4c  available    16
docker.c90ed50f9c1a633abce0cbc9cae0287c5ee6cd731b734374896d7e11a8caa065  c90ed50f9c1a633abce0cbc9cae0287c5ee6cd731b734374896d7e11a8caa065  available    16
docker.c9e008437a66b21ec7811fea06d6783426514f337d343c3dafa5b9ed1c717e76  c9e008437a66b21ec7811fea06d6783426514f337d343c3dafa5b9ed1c717e76  available    16
docker.ca0576e03bfb3465e01d9da9e0ed8d11160e5890f78e9226aa770d247b1d4e1d  ca0576e03bfb3465e01d9da9e0ed8d11160e5890f78e9226aa770d247b1d4e1d  available    16
docker.cassandra_data_1                                                  cassandra_data_1                                                  unavailable  16
docker.cassandra_data_2                                                  cassandra_data_2                                                  unavailable  16
docker.cassandra_data_3                                                  cassandra_data_3                                                  unavailable  16
docker.hdfs_datanode_1                                                   hdfs_datanode_1                                                   unavailable  16
docker.hdfs_datanode_2                                                   hdfs_datanode_2                                                   unavailable  16
docker.hdfs_datanode_3                                                   hdfs_datanode_3                                                   unavailable  16
docker.hdfs_datanode_4                                                   hdfs_datanode_4                                                   unavailable  16
docker.hdfs_datanode_5                                                   hdfs_datanode_5                                                   unavailable  16
docker.hdfs_namenode                                                     hdfs_namenode                                                     unavailable  16
```

## Ceph rbd info

The `docker/cassandra_data_1` image  has not been watching, but it is still unavailable?
```
$ rbd status docker/cassandra_data_1
Watchers: none
```

then I remove all hdfs containers in `xxx.xxx.xxx.206` host, but it is still watched.
```bash
$ rbd status docker/hdfs_datanode_5
Watchers:   
	watcher=xxx.xxx.xxx.206:0/1584367870 client.244412 cookie=1
```

I tried unmount `hdfs_datanode_5` by raxray.
```
# xxx.xxx.xxx.206
$ df -h
/dev/rbd0                           16G   45M   15G   1% /var/lib/libstorage/volumes/hdfs_datanode_5
```

```bash
$ rexray volume umount hdfs_datanode_5
FATA[0033] error unmounting volume                       error.status=500 volume=hdfs_datanode_5
```

## Test Experience
Rexray ceph/rbd volume is always unavailable in multi machine situations, Have you tested on multiple machines yet?

**Comment by codenrhoden** [comment]
Hi @JinsYin,

There's a lot to unpack here, so hopefully I can help out.  When it comes to volume status as reported by REX-Ray, you said you saw the following:

```docker.bf2e53a2d1d163449aed8c9d4c707247a326c25456ddeb7f671a0dca84be0477  bf2e53a2d1d163449aed8c9d4c707247a326c25456ddeb7f671a0dca84be0477  available    16
docker.bf403e33a5b1ff0cc3d2befbaeea531b82ac8e91dfe5157608daa1dbc9ce1071  bf403e33a5b1ff0cc3d2befbaeea531b82ac8e91dfe5157608daa1dbc9ce1071  available    16
docker.c17e8365fd9c375937f99eddd40b153b0185609e70b424263e685dd841d9911c  c17e8365fd9c375937f99eddd40b153b0185609e70b424263e685dd841d9911c  available    16
docker.c4fa07a2f7725b0b8e1c6a0837b6b263efabbfe6bfaa6272d7a61ec2662b6a4c  c4fa07a2f7725b0b8e1c6a0837b6b263efabbfe6bfaa6272d7a61ec2662b6a4c  available    16
docker.c90ed50f9c1a633abce0cbc9cae0287c5ee6cd731b734374896d7e11a8caa065  c90ed50f9c1a633abce0cbc9cae0287c5ee6cd731b734374896d7e11a8caa065  available    16
docker.c9e008437a66b21ec7811fea06d6783426514f337d343c3dafa5b9ed1c717e76  c9e008437a66b21ec7811fea06d6783426514f337d343c3dafa5b9ed1c717e76  available    16
docker.ca0576e03bfb3465e01d9da9e0ed8d11160e5890f78e9226aa770d247b1d4e1d  ca0576e03bfb3465e01d9da9e0ed8d11160e5890f78e9226aa770d247b1d4e1d  available    16
docker.cassandra_data_1                                                  cassandra_data_1                                                  unavailable  16
docker.cassandra_data_2                                                  cassandra_data_2                                                  unavailable  16
docker.cassandra_data_3                                                  cassandra_data_3                                                  unavailable  16
docker.hdfs_datanode_1                                                   hdfs_datanode_1                                                   unavailable  16
docker.hdfs_datanode_2                                                   hdfs_datanode_2                                                   unavailable  16
docker.hdfs_datanode_3                                                   hdfs_datanode_3                                                   unavailable  16
docker.hdfs_datanode_4                                                   hdfs_datanode_4                                                   unavailable  16
docker.hdfs_datanode_5                                                   hdfs_datanode_5                                                   unavailable  16
docker.hdfs_namenode                                                     hdfs_namenode                                                     unavailable  16
```

The `unavailable` here means that REX-Ray can tell that the volume is not available for mounting on the localhost. If the volume were already attached to the localhost, it will show up as `attached`. Because of the nature of RBD, it's actually hard to tell if a volume is attached to a host other than yourself, so right now the driver relies on whether the volume has any waters in the `rbd status` output, which it looks like you found.

If I'm reading your message correctly, you described the following scenario:
1. The `docker/hdfs_datanode_5` volume shows that it has a watcher from the `.206` host.
2. You removed all the containers from the `.206` host, but the RBD still shows a watcher at `.206`
3. You login to the `.206` host and see that the `docker/hdfs_datanode_5` volume is still mounted as `/dev/rbd0`
4. you try `rexray umount` for the volume and it doesn't work.

At step 3, the fact that the volume is still mounted is why the volume shows up as `unavailable` to other does. Until it is unmounted, no other nodes can use it. So the real question is why didn't Mesos unmount the volume? I don't know...
But, maybe it's because of the same reason that step 4 failed. If you were calling that from the `.206` host, that should work. I would need to see a debug log to be able to figure out why that call to `rexray umount` failed.

If you could enable debug logging in the rexray config file (usually at `/etc/rexray/config.yml`, but could be different with Mesos), restart the rexray service, then provide the debug log with that failed unmount, that would be very helpful.

Also, if you can provide your rexray config, that is also helpful.

**Comment by JinsYin** [comment]
@codenrhoden Thank you for your patient reply.

my current rexray config:
```
$ cat /etc/rexray/config.yml
rexray:
  logLevel: info
libstorage:
  logging:
    level: info
    httpRequests: true
    httpResponses: true
libstorage:
  service: rbd
rbd:
  defaultPool: rbd
```

In addition, my current rexray version is `0.8.2`, I plan to upgrade to the latest version and  eanble debug logging in rexray config file. I will re-test rexray and provide more detailed log information.

I will close the issue, if I have a new problem I will create a new issue. thx.
