### ISSUE TITLE
Cinder with DevStack: Authentication failure

### ISSUE THREAD

**Issue by sanjeevrsharma** [codedellemc/rexray#920]
# Summary
Authentication error while trying to use rexray with Cinder/DevStack

# Bug Reports
Not sure if it is a bug or just configuration issue

## Version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.1
OsArch: Linux-x86_64
Branch: v0.9.1
Commit: 2373541479478b817a8b143629e552f404f75226
Formed: Fri, 09 Jun 2017 15:23:38 EDT

libStorage
----------
SemVer: 0.6.1
OsArch: Linux-x86_64
Branch: v0.9.1
Commit: fd26f0ec72b077ffa7c82160fbd12a276e12c2ad

## Expected Behavior
 command  "rexray volume ls" should list all cinder volumes 

## Actual Behavior
Authentication error
ERRO[0000] error starting libStorage server              error.identityEndpoint="http://10.228.244.76/identity" error.provider=cinder error.tokenId= error.domainName= error.userId= error.password="******" error.tenantName=demo error.domainId= error.inner.Offset=5 error.availabilityZone= error.tenantId=ef00a81779a14006a10571c48ec83d67 error.trustId= error.userName=demo error.region= time=1499619432975
Oops, an error occured!

  error authenticating

## Steps To Reproduce
Install openstack devstack and collect all config to be used 
configure config.yml accordingly
run command rexray volume ls

## Configuration Files
rexray:
  logLevel: debug
libstorage:
  logging:
    level: debug
  service: cinder
  server:
    services:
      cinder:
        driver: cinder
cinder:
  authUrl: http://10.228.244.76/identity
  username: demo
  password: secret
  tenantName: demo
  tenantID: ef00a81779a14006a10571c48ec83d67

Devstack config
============

stack@DSIB0076:/etc/rexray$ env |grep "OS_"
OS_PROJECT_DOMAIN_ID=default
OS_REGION_NAME=RegionOne
OS_USER_DOMAIN_ID=default
OS_PROJECT_NAME=demo
OS_IDENTITY_API_VERSION=3
OS_PASSWORD=secret
OS_AUTH_TYPE=password
OS_AUTH_URL=http://10.228.244.76/identity
OS_USERNAME=demo
OS_TENANT_NAME=demo
OS_VOLUME_API_VERSION=2

### Service Log
DEBU[0000] created scoped scope                          new=libstorage.server.services.cinder parentScopes=libstorage.server,rexray,
DEBU[0000] got driver name                               driverName=cinder server=sprinkle-wolverine-ug service=cinder time=1499619296026
ERRO[0000] error starting libStorage server              error.userId= error.password="******" error.provider=cinder error.domainId= error.region= error.tokenId= error.tenantId=ef00a81779a14006a10571c48ec83d67 error.domainName= error.inner.Offset=5 error.trustId= error.userName=demo error.identityEndpoint="http://10.228.244.76/identity" error.tenantName=demo error.availabilityZone= time=1499619296345
Oops, an error occured!

  error authenticating

To correct the error please review:

  - Debug output by using the flag -l debug
  - The REX-ray website at https://github.com/codedellemc/rexray
  - The onâine heâp beâow

**Comment by codenrhoden** [comment]
@sanjeevrsharma Can you try setting the`authUrl` to , `http://10.228.244.76/identity/v3` or similar as exemplified in [this comment](https://github.com/codedellemc/libstorage/pull/243#issuecomment-297310994)?

**Comment by codenrhoden** [comment]
@sanjeevrsharma any progress?

**Comment by MatMaul** [comment]
and here it is :) like I just said in #863 we'll need to update gophercloud once this patch is in gophercloud/gophercloud#423

I have a workaround by redirecting requests at the apache level in devstack that allows to use http://10.228.244.76/v3 as an auth url, I'll post that on Monday, ping me if necessary.
