### ISSUE TITLE
Add generic NFS driver

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/rexray#962]
@codenrhoden commented on [Mon Mar 20 2017](https://github.com/codedellemc/libstorage/issues/474)

# Summary
A user expects to be able to work with generic NFS providers. The goal is to allow libStorage clients to mount network paths with custom mount options that may be necessary for optimizing connectivity. The benefit is that libStorage can become relevant to any storage platform that advertises NFS exports.

# New Feature
- User must be able to define custom mount options
- Docker does this natively and so does K8
- Can the “custom mount options” part of this be abstracted/generic enough to also work for ext4/XFS?
- Does this require an introduction of a new driver, or can the integration driver be refactored to allow direct access to the OS mount functionality? Server interaction is not required for this -- do we - want to enforce it for any reason? (same question/situation as #473)
- If server interaction is performed, do we just return success for attach/detach commands? Or should attach() perform a `showmount -e` command to verify that the NFS server has an export that is accessible to the client?

Goal:
Given an existing NFS server with valid export to a libStorage client, said client can call the libStorage Mount API with the remote network path and mount options (this implies dependence on #471)

**Comment by ceejatec** [comment]
Out of curiosity, why was this closed? It would indeed be a useful feaure; I found this page looking for exactly this capability.

**Comment by akutz** [comment]
Hi @ceejatec,

Because of [CSI-NFS](https://github.com/codedellemc/csi-nfs). It shipped with 0.10.0 and will be consumable via Docker in 0.11.0.

**Comment by ceejatec** [comment]
Thanks!

**Comment by rockrockovic** [comment]
sorry for reopen, but how to use nfs with rexray?
