### ISSUE TITLE
Revamp how volume sizes are handled

### ISSUE THREAD

**Issue by codenrhoden** [codedellemc/rexray#973]
@codenrhoden commented on [Wed Mar 29 2017](https://github.com/codedellemc/libstorage/issues/491)

This Epic tracks several issues related to handling and parsing volume sizes.

The overall goal is to allow for volumes specified in bytes at the API level, and for sizes to be given with suffixes (e.g. "16G", "1T", etc.).

**Comment by akutz** [comment]
Hi @codenrhoden,

I'm closing this as it's going to be moot with CSI. If you disagree please feel free to reopen.
