### ISSUE TITLE
rexray.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by josefroselinfonova** [codedellemc/rexray#977]
# Summary
I want to use the Docker Volume Plugin for Cinder on a CoreOS host in OpenStack Nova,
but following error keeps poping up when I want to install the plugin:

```shell
Error response from daemon: dial unix /run/docker/plugins/9dba85760ad3e5293eda1983682046833892891454e44f1104ee24e37afd7c06/rexray.sock: connect: no such file or directory
```
Error seems similar to:
#https://github.com/codedellemc/rexray/issues/820
But I did not get any information about wrong permissions.

## Version
(from my docker service logs)

```shell
$ rexray version
REX-Ray
-------
Binary: /usr/bin/rexray
Flavor: client+agent+controller
SemVer: 0.9.2
OsArch: Linux-x86_64
Branch: v0.9.2
Commit: 9c7b7329884bf2feeffe101fc5dc3a239730427d
Formed: Wed, 28 Jun 2017 20:15:03 UTC

libStorage
----------
SemVer: 0.6.2
OsArch: Linux-x86_64
Branch: v0.9.2
Commit: 7368564cc71be9a0dbe03ddfbaeda281232eee72
Formed: Wed, 28 Jun 2017 20:14:42 UTC

Docker 17.05.0-ce
Container Linux by CoreOS alpha (1492.1.0)
```

## Expected Behavior
The plugin should install successfully or give a meaningful error output in the service logs 

## Actual Behavior
This is the point in the service logs, where I can see that something fails:
level=info msg=\"received exit signal\" signal=terminated time=1502793444792 "

## Steps To Reproduce
Just install the plugin
```shell
docker plugin install rexray/cinder \
  CINDER_AUTHURL=http://1.2.3.4:35357/v2.0 \
  CINDER_USERNAME=username \
  CINDER_PASSWORD=password \
  CINDER_TENANTNAME=project_rancher
```

```shell
Error response from daemon: dial unix /run/docker/plugins/9dba85760ad3e5293eda1983682046833892891454e44f1104ee24e37afd7c06/rexray.sock: connect: no such file or directory
```

## Configuration Files
No real config files, as config is passed into the plugin via env variables:
```shell
docker plugin install rexray/cinder \
  CINDER_AUTHURL=http://1.2.3.4:35357/v2.0 \
  CINDER_USERNAME=username \
  CINDER_PASSWORD=password \
  CINDER_TENANTNAME=project_rancher
```

## Logs
The attached log file shows the docker log output of following commands:
```shell

docker plugin install rexray/cinder   CINDER_AUTHURL=.... (like above)
docker plugin list
docker plugin set 9dba85760ad3 REXRAY_LOGLEVEL=debug
docker plugin enable rexray/cinder 
```

[docker-log.txt](https://github.com/codedellemc/rexray/files/1224848/docker-log.txt)

**Comment by clintkitson** [comment]
@josefroselinfonova Can you re-run and add the `REXRAY_DEBUG=true` flag? It is very likely that you are having auth problems relating to the combination of credentials you are using.

**Comment by josefroselinfonova** [comment]
Hi Clint, thank you for your response.
I tried that, but this does not seem to be a valid env var for the plugin:

```
Status: Downloaded newer image for rexray/cinder:edge
Error response from daemon: setting "REXRAY_DEBUG" not found in the plugin configuration
```

But you are right about your guess having auth problems. I switched to v3

docker plugin install rexray/cinder:edge \
  CINDER_AUTHURL=http://172.31.241.5:5000/v3 \
  CINDER_USERNAME=#### \
  CINDER_PASSWORD=##### \
  CINDER_TENANTNAME=##### \
  CINDER_DOMAINNAME=##### \
  REXRAY_LOGLEVEL=debug

**Comment by josefroselinfonova** [comment]
Hi Clint, thank you for your response.
I tried that, but this does not seem to be a valid env var for the plugin:

```
Status: Downloaded newer image for rexray/cinder:edge
Error response from daemon: setting "REXRAY_DEBUG" not found in the plugin configuration
```
You probably were thinking about REXRAY_LOGLEVEL=debug 
That gave me the same result in the logs as before. 


But you are right about your guess having auth problems. I switched to v3

docker plugin install rexray/cinder:edge \
  CINDER_AUTHURL=http://172.31.241.5:5000/v3 \
  CINDER_USERNAME=#### \
  CINDER_PASSWORD=##### \
  CINDER_TENANTNAME=##### \
  CINDER_DOMAINNAME=##### \
  REXRAY_LOGLEVEL=debug

And that seems to give better feedback:
[v3-plugin.txt](https://github.com/codedellemc/rexray/files/1225632/v3-plugin.txt)

```panic: runtime error: comparing uncomparable type gophercloud.ErrDefault401```

My question now is: What permission do I need to get the plugin running, as this is a production installation, I will not get admin permissions on there. The user I supply to the plugin can view, edit, delete, create volumes via the OpenStack Horizon GUI.

**Comment by clintkitson** [comment]
@josefroselinfonova My fault, that was the variable I was thinking of. It looks like the error you are getting is in relation to the v3 endpoint which our bindings don't look to support quite yet.

Here is the PR in the bindings showing the progress on getting it merged into the upstream gophercloud project.
https://github.com/gophercloud/gophercloud/pull/415

**Comment by josefroselinfonova** [comment]
I basically can not find any recommendations for setting the permissions right for the plugin. Is there a documentation for that?
I see that the authentication failed on keystone, so it is pretty sure my issue.

**Comment by clintkitson** [comment]
We haven't had anyone run into this issue yet. My suggestion would be to try and recreate a couple of the steps that REX goes through but manually through the GUI.

- Create volume
- Attach volume to VM

**Comment by clintkitson** [comment]
@MatMaul Any idea here?

**Comment by MatMaul** [comment]
It is not related to gophercloud/gophercloud#415 , we are talking Keystone version here and v3 is supported by gophercloud since a while.
No idea why it would fail with the docker plugin only.
@clintkitson can you investigate this on master ? I can't test anything since libstorage merge.
https://github.com/codedellemc/libstorage/pull/594

**Comment by clintkitson** [comment]
@josefroselinfonova One thing you can do is use the `docker-runc` command to actually enter the container the was created for the REX-Ray plugin. From there you can interactively use the `rexray` command to troubleshoot further.

Interesting information about it not working from the plugin but working from the OS itself. Can you get a log from the plugin when you are using the exact same config options, ie. authurl?

**Comment by josefroselinfonova** [comment]
The main difference between the plugin and running it directly is, that I have the config.yml on the one side and the env vars when I want to install the plugin. Do you see any possiblity to give a config.yml to the plugin. When I try running the binary directly, it also fails, when I configure it the same way as the plugin:

/etc/rexray/config.yml
``` yml
rexray:
  logLevel: debug
libstorage:
  logging:
    level: debug
  service: cinder
  integration:
    volume:
      operations:
        create:
          default:
            size: 5
cinder:
  authURL: ####
  userName: ####
  password: ####
  tenantName: ####
  domainName: #####
```

Docker plugin install
``` 
docker plugin install rexray/cinder:edge \
  CINDER_AUTHURL=#### \
  CINDER_USERNAME=#### \
  CINDER_PASSWORD=#### \
  CINDER_TENANTNAME=#### \
CINDER_DOMAINNAME=#### \
REXRAY_LOGLEVEL=debug
```

Rexray env:
```
REXRAY_LOGLEVEL=debug
REXRAY_LIBSTORAGE_LOGGING_LEVEL=debug
LIBSTORAGE_SERVICE=cinder
CINDER_USERNAME=####
CINDER_TENANTNAME=####
CINDER_DOMAINNAME=####
CINDER_AUTHURL=####
CINDER_PASSWORD=####
```

**Comment by josefroselinfonova** [comment]
When I env vars, I get following error:
```
core@grzosrancheragent03 /etc/rexray $ sudo  rexray volume ls
ERRO[0000] error starting libStorage server              error.configKey=libstorage.server.services error.obj=<nil> time=1502963566650
```
I can not find any LIBSTORAGE_SERVER_SERVICES env (guessed from libstorage.server.services) 
```
core@grzosrancheragent03 /etc/rexray $ rexray env | grep SERVICE
INFO[0000] updated log level                             logLevel=debug
DEBU[0000] os.args                                       time=1502963498361 val=[rexray env]
LIBSTORAGE_SERVICE=cinder
DEBU[0000] completed cli execution                       time=1502963498458
REXRAY_SERVICE=cinder
INFO[0000] exiting process                               time=1502963498458
REXRAY_LIBSTORAGE_SERVICE=cinder
DEBU[0000] completed onExit at end of program            time=1502963498458
```

Maybe when I can fix my problem using the env vars, I can also run the plugin installation.
To docker-runc, I do not really see a container running docker ps -a. I tried out of the blue, but failed:
```
core@grzosrancheragent03 /etc/rexray $ docker-runc ps rexray/cinder:edge
open /run/runc/rexray/cinder:edge/state.json: permission denied
core@grzosrancheragent03 /etc/rexray $ sudo !!
sudo docker-runc ps rexray/cinder:edge
container "rexray/cinder:edge" does not exist
```

**Comment by clintkitson** [comment]
You need to find the proper id of the container that is/was running RR under the `docker-runc` list of containers or in the `/run/runc` directory.

Make sure to clear out your env variables. `LIBSTORAGE_SERVICE` is the only env variable that should be specified relating to services.

For example `LIBSTORAGE_SERVICE=ec2 rexray start -f`. You would also expand it in the cinder case as follows..

`LIBSTORAGE_SERVICE=cinder CINDER_USERNAME=xxx rexray volume ls`

**Comment by fbiaustria** [comment]
I just tried installing the plugin again today and it succeded. It works now with keystone v2, but not v3, which is ok for me.

This is the log file while trying to install the plugin with the v3 authurl:
[v3-error.txt](https://github.com/codedellemc/rexray/files/1233690/v3-error.txt)

**Comment by clintkitson** [comment]
@fbiaustria Anything different from your side that made it work this time?

**Comment by josefroselinfonova** [comment]
I used the wrong auth url, or more specific the wrong port, typical layer 8 problem right here. Sorry for your time.

**Comment by ravshan1972** [comment]
Hi, I have the same issue while trying to install plugin on Ubuntu 22.04

latest: Pulling from rexray/ebs
Digest: sha256:bbe1cfc5241d765c735e1d80fd790a0fc50e2e7064239255c4b61397a16c3355
713b84867e46: Complete
Error response from daemon: dial unix /run/docker/plugins/234346d5a594eac85a189c39d52320c25ea874251d9f8d2b78408de0780bb64c/rexray.sock: connect: no such file or directory
