### ISSUE TITLE
Docker S3FS appending /data to bucket mountpoint

### ISSUE THREAD

**Issue by wadevogt** [codedellemc/rexray#994]
# Summary
When mounting an existing S3 bucket using the Docker volume plugin, it automatically mounts to a folder called "/data" in the bucket and there doesn't seem to be a way to change that. If "/data" doesn't exist it creates it.

## Version
Docker: 17.06.1-ce
Docker rexray/s3fs: 0.9.2

## Expected Behavior
I was expecting the volume to mount to the root of my S3 bucket, so that I can access all the data in the bucket.

## Actual Behavior
The volume is mounted to a folder called "/data" in my S3 bucket. The mount is successful and I can access files I put in that folder. I just can't access anything else in the bucket that isn't under /data.

## Steps To Reproduce
1. Create an S3 bucket using the AWS console, and upload a file to it.
2. Install the rexray/s3fs docker volume plugin using your AWS credentials.
3. Create a docker-compose.yml that specifies the volume, and mounts it to a service. (see below)
4. Inspect the volume, and a "/data" is appended to the end of the Mountpoint.

## Configuration Files
docker-compose.yml
`version: "3"

services:
  httpd-test:
    image: httpd:latest
    volumes:
      - my-bucket:/opt/my-bucket

volumes:
  my-bucket:
    external: true`

BEFORE STARTING CONTAINER
docker volume inspect my-vol
`[
    {
        "Driver": "rexray/s3fs:latest",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/plugins/b34ac7df28a003a604f9f85dbc6d8f587ca9f8a2e64a84a894abb8c05c8bb3fb/rootfs",
        "Name": "my-bucket",
        "Options": {},
        "Scope": "global",
        "Status": {
            "availabilityZone": "",
            "fields": null,
            "iops": 0,
            "name": "my-bucket",
            "server": "s3fs",
            "service": "s3fs",
            "size": 0,
            "type": ""
        }
    }
]
`

AFTER STARTING CONTAINER
docker volume inspect my-vol
`[
    {
        "Driver": "rexray/s3fs:latest",
        "Labels": null,
        "Mountpoint": "/var/lib/docker/plugins/b34ac7df28a003a604f9f85dbc6d8f587ca9f8a2e64a84a894abb8c05c8bb3fb/rootfs/var/lib/libstorage/volumes/my-bucket/data",
        "Name": "my-bucket",
        "Options": {},
        "Scope": "global",
        "Status": {
            "availabilityZone": "",
            "fields": null,
            "iops": 0,
            "name": "my-bucket",
            "server": "s3fs",
            "service": "s3fs",
            "size": 0,
            "type": ""
        }
    }
]
`

**Comment by clintkitson** [comment]
Hello @wadevogt. The default path for REX-Ray to mount inside of a volume is at the following location.

`LIBSTORAGE_VOLUME_OPERATIONS_MOUNT_ROOT_PATH = /data`. 

This is done to ensure filesystem stubs are not present, ie. lost+found. If you desire to change this you can flip this setting to be `/` or any other path of choice.

**Comment by wadevogt** [comment]
Thanks @clintkitson. How do I change that setting for the docker volume plugin? 

I don't see anything in the documentation for the plugin that allows that: https://rexray.readthedocs.io/en/stable/user-guide/docker-plugins/#simple-storage-service

**Comment by clintkitson** [comment]
You're right it isn't passed as an option to Docker currently but is available in standalone mode.

https://github.com/codedellemc/rexray/blob/master/.docker/plugins/s3fs/config.json#L13-L62

**Comment by wadevogt** [comment]
Thanks for the confirmation. I really like the plugin, and hope that this option will be added in a future version.

**Comment by dahendel** [comment]
Would PR #1042 resolve this? It also adds the S3FS_ENDPOINT env variable for custom s3 endpoints.

**Comment by clintkitson** [comment]
Yes @dahendel

**Comment by clintkitson** [comment]
The issue tracking this for the next release is https://github.com/codedellemc/rexray/issues/1043

**Comment by codenrhoden** [comment]
Closed by #1042
